### ISSUE TITLE
Request textDocument/hover failed.

### ISSUE THREAD

**Issue by vibhanshu909** [sveltejs/language-tools#1116]
Getting the following error:
```bash
TypeError: must pass in a file:// URI to convert to a file path
    at Object.fileUriToPath (/home/anonymous/.vscode/extensions/ardenivanov.svelte-intellisense-0.7.1/server/out/utils.js:25:15)
    at reloadDocument (/home/anonymous/.vscode/extensions/ardenivanov.svelte-intellisense-0.7.1/server/out/server.js:69:70)
    at /home/anonymous/.vscode/extensions/ardenivanov.svelte-intellisense-0.7.1/server/out/server.js:60:5
    at CallbackList.invoke (/home/anonymous/.vscode/extensions/ardenivanov.svelte-intellisense-0.7.1/server/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/home/anonymous/.vscode/extensions/ardenivanov.svelte-intellisense-0.7.1/server/node_modules/vscode-jsonrpc/lib/events.js:120:36)
    at /home/anonymous/.vscode/extensions/ardenivanov.svelte-intellisense-0.7.1/server/node_modules/vscode-languageserver/lib/main.js:181:38
    at handleNotification (/home/anonymous/.vscode/extensions/ardenivanov.svelte-intellisense-0.7.1/server/node_modules/vscode-jsonrpc/lib/main.js:489:43)
    at processMessageQueue (/home/anonymous/.vscode/extensions/ardenivanov.svelte-intellisense-0.7.1/server/node_modules/vscode-jsonrpc/lib/main.js:260:17)
    at Immediate._onImmediate (/home/anonymous/.vscode/extensions/ardenivanov.svelte-intellisense-0.7.1/server/node_modules/vscode-jsonrpc/lib/main.js:247:13)
    at processImmediate (internal/timers.js:461:21)
[Error - 5:59:56 pm] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: must pass in a file:// URI to convert to a file path
  Code: -32603
```
Whenever I view the diff of a file from source control in vscode, and hover over the file contents I get the following error from the Svelte Intellisense Language Server.

![Screenshot from 2021-07-24 18-01-44](https://user-images.githubusercontent.com/26433047/126868524-88771581-1295-4218-a163-df34d34e9e1d.png)

 - OS: Ubuntu 20.04.2 LTS
 - IDE: VSCode
 - Plugin/Package: [`Svelte for VSCode`, or `svelte-language-server`]

**Comment by jasonlyu123** [comment]
The error it's from the svelte intellisense extension. Not the svelte for vs code extension.

**Comment by paolodina** [comment]
https://github.com/ArdenIvanov/svelte-intellisense/issues/56
