### ISSUE TITLE
Emmet only works some of the time

### ISSUE THREAD

**Issue by kswope** [sveltejs/language-tools#1175]
**Describe the bug**
completions only sporadically available

https://user-images.githubusercontent.com/321586/133140763-313199c7-eee3-419f-9087-cef8ff2b696d.mov

**System (please complete the following information):**
 - OS: mac
 - IDE: VScode
 - Plugin/Package: Svelte for VS Code
 - Vim emulation mode (maybe relevant)

heisenbug was spotted here but never resolved

https://github.com/sveltejs/language-tools/issues/651

**Comment by jasonlyu123** [comment]
I can't reproduce it. Can you try with this config `"svelte.trace.server": "messages"` and post the log in the output channel? It's near the integrated terminal, chose svelte in the dropdown.

**Comment by kswope** [comment]
Starting on a empty buffer this is the output from one successful emmet "div" completion and one missing emmet "div" completion.  Something is not happy.

```
[Trace - 3:07:24 AM] Sending notification '$/setTrace'.
[Trace - 3:07:24 AM] Sending notification 'textDocument/didChange'.
[Trace - 3:07:24 AM] Sending request 'textDocument/completion - (177)'.
[Trace - 3:07:24 AM] Received response 'textDocument/completion - (177)' in 29ms.
[Trace - 3:07:24 AM] Sending request 'completionItem/resolve - (178)'.
[Trace - 3:07:24 AM] Received response 'completionItem/resolve - (178)' in 0ms.
[Trace - 3:07:24 AM] Sending notification 'textDocument/didChange'.
[Trace - 3:07:24 AM] Sending request 'textDocument/completion - (179)'.
[Trace - 3:07:25 AM] Received response 'textDocument/completion - (179)' in 21ms.
[Trace - 3:07:25 AM] Sending request 'completionItem/resolve - (180)'.
[Trace - 3:07:25 AM] Received response 'completionItem/resolve - (180)' in 0ms.
[Trace - 3:07:25 AM] Sending notification 'textDocument/didChange'.
[Trace - 3:07:25 AM] Sending request 'textDocument/completion - (181)'.
[Trace - 3:07:25 AM] Received response 'textDocument/completion - (181)' in 15ms.
[Trace - 3:07:25 AM] Sending request 'completionItem/resolve - (182)'.
[Trace - 3:07:25 AM] Received response 'completionItem/resolve - (182)' in 0ms.
[Trace - 3:07:25 AM] Sending request 'textDocument/codeAction - (183)'.
[Trace - 3:07:25 AM] Received response 'textDocument/codeAction - (183)' in 1ms.
Using Svelte v3.42.5 from /Users/kevin/Development/css-practice/node_modules/svelte/compiler
[Trace - 3:07:25 AM] Sending request 'textDocument/documentColor - (184)'.
Using Svelte v3.42.5 from /Users/kevin/Development/css-practice/node_modules/svelte/compiler
[Trace - 3:07:25 AM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 3:07:26 AM] Sending notification 'textDocument/didChange'.
[Trace - 3:07:26 AM] Sending request 'textDocument/codeAction - (185)'.
[Trace - 3:07:26 AM] Received response 'textDocument/codeAction - (185)' in 1ms.
Using Svelte v3.42.5 from /Users/kevin/Development/css-practice/node_modules/svelte/compiler
Using Svelte v3.42.5 from /Users/kevin/Development/css-practice/node_modules/svelte/compiler
[Trace - 3:07:26 AM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 3:07:27 AM] Sending request 'textDocument/documentColor - (186)'.
[Trace - 3:07:27 AM] Sending notification 'textDocument/didChange'.
[Trace - 3:07:27 AM] Sending request 'textDocument/codeAction - (187)'.
[Trace - 3:07:27 AM] Received response 'textDocument/codeAction - (187)' in 1ms.
[Trace - 3:07:28 AM] Sending notification '$/setTrace'.
[Trace - 3:07:28 AM] Received response 'textDocument/documentColor - (186)' in 1003ms.
Using Svelte v3.42.5 from /Users/kevin/Development/css-practice/node_modules/svelte/compiler
Using Svelte v3.42.5 from /Users/kevin/Development/css-practice/node_modules/svelte/compiler
[Trace - 3:07:28 AM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 3:07:28 AM] Sending notification 'textDocument/didChange'.
[Trace - 3:07:28 AM] Sending notification '$/setTrace'.
[Trace - 3:07:28 AM] Sending request 'textDocument/documentColor - (188)'.
[Trace - 3:07:28 AM] Sending notification 'textDocument/didChange'.
[Trace - 3:07:28 AM] Sending request 'textDocument/completion - (189)'.
Error: Debug Failure. False expression: Paths must either both be absolute or both be relative
    at Object.getRelativePathFromDirectory (/Users/kevin/.vscode/extensions/svelte.svelte-vscode-105.4.0/node_modules/typescript/lib/typescript.js:6528:18)
    at getLocalModuleSpecifier (/Users/kevin/.vscode/extensions/svelte.svelte-vscode-105.4.0/node_modules/typescript/lib/typescript.js:117000:80)
    at computeModuleSpecifiers (/Users/kevin/.vscode/extensions/svelte.svelte-vscode-105.4.0/node_modules/typescript/lib/typescript.js:116967:33)
    at Object.getModuleSpecifiersWithCacheInfo (/Users/kevin/.vscode/extensions/svelte.svelte-vscode-105.4.0/node_modules/typescript/lib/typescript.js:116927:26)
    at getModuleSpecifiers (/Users/kevin/.vscode/extensions/svelte.svelte-vscode-105.4.0/node_modules/typescript/lib/typescript.js:146057:72)
    at /Users/kevin/.vscode/extensions/svelte.svelte-vscode-105.4.0/node_modules/typescript/lib/typescript.js:146060:26
    at Object.flatMap (/Users/kevin/.vscode/extensions/svelte.svelte-vscode-105.4.0/node_modules/typescript/lib/typescript.js:713:25)
    at getNewImportFixes (/Users/kevin/.vscode/extensions/svelte.svelte-vscode-105.4.0/node_modules/typescript/lib/typescript.js:146059:28)
    at Object.getModuleSpecifierForBestExportInfo (/Users/kevin/.vscode/extensions/svelte.svelte-vscode-105.4.0/node_modules/typescript/lib/typescript.js:145909:22)
    at Object.tryResolve (/Users/kevin/.vscode/extensions/svelte.svelte-vscode-105.4.0/node_modules/typescript/lib/typescript.js:126471:47)
[Trace - 3:07:29 AM] Received response 'textDocument/completion - (189)' in 81ms.
[Trace - 3:07:29 AM] Sending notification 'textDocument/didChange'.
[Trace - 3:07:29 AM] Sending notification 'textDocument/didChange'.
[Trace - 3:07:29 AM] Sending request 'textDocument/codeAction - (190)'.
[Trace - 3:07:29 AM] Received response 'textDocument/codeAction - (190)' in 2ms.
Using Svelte v3.42.5 from /Users/kevin/Development/css-practice/node_modules/svelte/compiler
[Trace - 3:07:29 AM] Sending request 'textDocument/documentColor - (191)'.
Using Svelte v3.42.5 from /Users/kevin/Development/css-practice/node_modules/svelte/compiler
[Trace - 3:07:29 AM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 3:07:30 AM] Received response 'textDocument/documentColor - (184)' in 4135ms.
[Trace - 3:07:30 AM] Received response 'textDocument/documentColor - (188)' in 2002ms.
[Trace - 3:07:30 AM] Received response 'textDocument/documentColor - (191)' in 1026ms.
[Trace - 3:07:31 AM] Sending request 'textDocument/documentSymbol - (192)'.
[Trace - 3:07:32 AM] Received response 'textDocument/documentSymbol - (192)' in 1011ms.
[Trace - 3:07:45 AM] Sending notification '$/setTrace'.
[Trace - 3:07:48 AM] Sending notification '$/setTrace'.
[Trace - 3:07:52 AM] Sending notification '$/setTrace'.
```

**Comment by jasonlyu123** [comment]
Do you have a reproducible? It might have something to do with the error from typescript. Or if you can't find a minimal reproducible you can also follow the [development guide](https://github.com/sveltejs/language-tools#development) to debug why the error is thrown.

**Comment by jasonlyu123** [comment]
Can you still reproduce the problem?  I can reproduce the error in the stack trace. But I can't reproduce it in emmet. 

I am suspecting the problem might be because of some typescript completion error causing it to error out. But we have added a few checks for typescript completion in the past few months to solve a related issue. As a side effort, The majority of the places where you might trigger emmet completion would not trigger a typescript completion anymore.

**Comment by ambersnow** [comment]
Hi, wanted to tag in and say I am running into the same issue. Everything was working fine until I upgraded to Sveltekit 1.0.0-next.360 and that's when I noticed autocompletion not working anymore altogether.

Svelte extension on messages log level:

```
[Trace - 1:20:30 PM] Received response 'textDocument/completion - (49)' in 77ms.
[Trace - 1:20:30 PM] Sending request 'textDocument/codeAction - (50)'.
[Trace - 1:20:30 PM] Received response 'textDocument/codeAction - (50)' in 2ms.
[Trace - 1:20:30 PM] Sending notification 'textDocument/didChange'.
[Trace - 1:20:30 PM] Sending request 'textDocument/completion - (51)'.
Error: Debug Failure. False expression: Paths must either both be absolute or both be relative
    at Object.getRelativePathFromDirectory (/home/ubuntu/.vscode-server/extensions/svelte.svelte-vscode-105.18.1/node_modules/typescript/lib/typescript.js:8175:18)
    at getLocalModuleSpecifier (/home/ubuntu/.vscode-server/extensions/svelte.svelte-vscode-105.18.1/node_modules/typescript/lib/typescript.js:122135:80)
    at computeModuleSpecifiers (/home/ubuntu/.vscode-server/extensions/svelte.svelte-vscode-105.18.1/node_modules/typescript/lib/typescript.js:122102:33)
    at Object.getModuleSpecifiersWithCacheInfo (/home/ubuntu/.vscode-server/extensions/svelte.svelte-vscode-105.18.1/node_modules/typescript/lib/typescript.js:122057:26)
    at getModuleSpecifiers (/home/ubuntu/.vscode-server/extensions/svelte.svelte-vscode-105.18.1/node_modules/typescript/lib/typescript.js:153381:81)
    at /home/ubuntu/.vscode-server/extensions/svelte.svelte-vscode-105.18.1/node_modules/typescript/lib/typescript.js:153385:26
    at Object.flatMap (/home/ubuntu/.vscode-server/extensions/svelte.svelte-vscode-105.18.1/node_modules/typescript/lib/typescript.js:702:25)
    at getNewImportFixes (/home/ubuntu/.vscode-server/extensions/svelte.svelte-vscode-105.18.1/node_modules/typescript/lib/typescript.js:153383:28)
    at getFixesForAddImport (/home/ubuntu/.vscode-server/extensions/svelte.svelte-vscode-105.18.1/node_modules/typescript/lib/typescript.js:153408:77)
    at getImportFixes (/home/ubuntu/.vscode-server/extensions/svelte.svelte-vscode-105.18.1/node_modules/typescript/lib/typescript.js:153195:22)
[Trace - 1:20:30 PM] Received response 'textDocument/completion - (51)' in 57ms.
[Trace - 1:20:30 PM] Sending notification 'textDocument/didChange'.
[Trace - 1:20:30 PM] Sending notification 'textDocument/didChange'.
[Trace - 1:20:31 PM] Sending request 'textDocument/documentColor - (52)'.
[Trace - 1:20:31 PM] Sending request 'textDocument/codeAction - (53)'.
[Trace - 1:20:31 PM] Received response 'textDocument/codeAction - (53)' in 1ms.
[Trace - 1:20:31 PM] Sending request 'textDocument/semanticTokens/full - (54)'.
Using Svelte v3.48.0 from /home/ubuntu/Work/project-name/node_modules/svelte/compiler
Using Svelte v3.48.0 from /home/ubuntu/Work/project-name/node_modules/svelte/compiler
[Trace - 1:20:31 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 1:20:31 PM] Sending request 'textDocument/codeAction - (55)'.
[Trace - 1:20:31 PM] Received response 'textDocument/codeAction - (55)' in 1ms.
[Trace - 1:20:32 PM] Received response 'textDocument/documentColor - (52)' in 1001ms.
[Trace - 1:20:32 PM] Received response 'textDocument/semanticTokens/full - (54)' in 1022ms.
[Trace - 1:20:32 PM] Sending request 'textDocument/documentSymbol - (56)'.
[Trace - 1:20:33 PM] Received response 'textDocument/documentSymbol - (56)' in 1002ms.
[Trace - 1:21:26 PM] Sending notification '$/setTrace'.
[Trace - 1:21:26 PM] Sending request 'textDocument/semanticTokens/range - (57)'.
[Trace - 1:21:27 PM] Received response 'textDocument/semanticTokens/range - (57)' in 1002ms.
[Trace - 1:21:27 PM] Sending request 'textDocument/semanticTokens/full - (58)'.
[Trace - 1:21:28 PM] Received response 'textDocument/semanticTokens/full - (58)' in 1002ms.
```

Version of extension: 105.18.1

npm packages:
```
project
├── @sveltejs/adapter-auto@1.0.0-next.54
├── @sveltejs/adapter-node@1.0.0-next.78
├── @sveltejs/kit@1.0.0-next.360
├── @tailwindcss/forms@0.4.1
├── autoprefixer@10.4.7
├── cookie@0.4.2
├── dayjs@1.11.3
├── eslint-config-prettier@8.5.0
├── eslint-plugin-svelte3@3.4.1
├── eslint@7.32.0
├── fast-xml-parser@4.0.8
├── html2canvas@1.4.1
├── node-sass@7.0.1
├── postcss-load-config@3.1.4
├── postcss@8.4.14
├── prettier-plugin-svelte@2.7.0
├── prettier@2.7.1
├── sass@1.53.0
├── svelte-hero-icons@3.1.2
├── svelte-lucide-icons@0.2.0
├── svelte-popperjs@1.2.10
├── svelte-portal@2.2.0
├── svelte-preprocess@4.10.7
├── svelte@3.48.0
├── tailwindcss@3.1.4
└── vite@2.9.13
```

But the issue goes away if I switch to a project that I have not upgraded to sveltekit v360 yet. On a project running v348 extension works perfectly normally.

The npm versions for the other project that has no issues:

```
├── @sveltejs/adapter-auto@1.0.0-next.50
├── @sveltejs/adapter-node@1.0.0-next.78
├── @sveltejs/kit@1.0.0-next.348
├── @tailwindcss/forms@0.4.1
├── autoprefixer@10.4.7
├── cookie@0.4.2
├── eslint-config-prettier@8.5.0
├── eslint-plugin-svelte3@3.4.1
├── eslint@7.32.0
├── fast-xml-parser@4.0.8
├── lucide-svelte@0.44.0
├── node-sass@7.0.1
├── postcss-load-config@3.1.4
├── postcss@8.4.14
├── prettier-plugin-svelte@2.7.0
├── prettier@2.6.2
├── svelte-popperjs@1.2.10
├── svelte-portal@2.2.0
├── svelte-preprocess@4.10.7
├── svelte@3.48.0
└── tailwindcss@3.0.24
```

Svelte extension output on messages log level
```
[Trace - 1:24:28 PM] Sending notification 'textDocument/didChange'.
[Trace - 1:24:28 PM] Sending notification '$/cancelRequest'.
[Trace - 1:24:28 PM] Sending notification '$/cancelRequest'.
[Trace - 1:24:28 PM] Sending request 'textDocument/signatureHelp - (37)'.
[Trace - 1:24:28 PM] Sending notification 'textDocument/didChange'.
[Trace - 1:24:28 PM] Sending notification '$/cancelRequest'.
[Trace - 1:24:28 PM] Sending notification '$/cancelRequest'.
[Trace - 1:24:28 PM] Sending request 'textDocument/signatureHelp - (38)'.
[Trace - 1:24:28 PM] Sending notification 'textDocument/didChange'.
[Trace - 1:24:28 PM] Received response 'textDocument/signatureHelp - (16)' in 1102ms.
[Trace - 1:24:28 PM] Received response 'textDocument/documentColor - (4)' in 3282ms.
[Trace - 1:24:28 PM] Sending notification '$/cancelRequest'.
[Trace - 1:24:28 PM] Sending request 'textDocument/signatureHelp - (39)'.
[Trace - 1:24:28 PM] Received response 'textDocument/documentSymbol - (8)' in 3233ms.
[Trace - 1:24:28 PM] Sending notification 'textDocument/didChange'.
[Trace - 1:24:28 PM] Received response 'textDocument/documentSymbol - (10)' in 2810ms.
[Trace - 1:24:29 PM] Received response 'textDocument/documentColor - (11)' in 2896ms.
[Trace - 1:24:29 PM] Sending notification '$/cancelRequest'.
[Trace - 1:24:29 PM] Sending request 'textDocument/signatureHelp - (40)'.
[Trace - 1:24:29 PM] Received response 'textDocument/semanticTokens/range - (13)' in 2411ms.
[Trace - 1:24:29 PM] Received response 'textDocument/completion - (17)' in 1263ms.
[Trace - 1:24:29 PM] Received response 'textDocument/completion - (18)' in 1358ms.
[Trace - 1:24:29 PM] Sending request 'textDocument/codeAction - (41)'.
[Trace - 1:24:29 PM] Sending notification 'textDocument/didChange'.
[Trace - 1:24:29 PM] Sending notification '$/cancelRequest'.
[Trace - 1:24:29 PM] Received response 'textDocument/completion - (19)' in 1393ms.
[Trace - 1:24:29 PM] Sending request 'textDocument/documentColor - (42)'.
[Trace - 1:24:29 PM] Received response 'textDocument/completion - (20)' in 1451ms.
[Trace - 1:24:29 PM] Sending notification '$/cancelRequest'.
[Trace - 1:24:29 PM] Sending request 'textDocument/signatureHelp - (43)'.
[Trace - 1:24:29 PM] Sending notification 'textDocument/didChange'.
[Trace - 1:24:29 PM] Received response 'textDocument/completion - (21)' in 1521ms.
[Trace - 1:24:29 PM] Sending request 'textDocument/documentSymbol - (44)'.
[Trace - 1:24:29 PM] Received response 'textDocument/completion - (22)' in 1577ms.
[Trace - 1:24:29 PM] Received response 'textDocument/completion - (23)' in 1596ms.
[Trace - 1:24:29 PM] Sending notification '$/cancelRequest'.
[Trace - 1:24:29 PM] Sending request 'textDocument/signatureHelp - (45)'.
[Trace - 1:24:29 PM] Received response 'textDocument/completion - (24)' in 1643ms.
[Trace - 1:24:29 PM] Received response 'textDocument/completion - (25)' in 1702ms.
[Trace - 1:24:29 PM] Sending notification 'textDocument/didChange'.
[Trace - 1:24:29 PM] Sending request 'textDocument/completion - (46)'.
[Trace - 1:24:29 PM] Received response 'textDocument/completion - (26)' in 1717ms.
[Trace - 1:24:29 PM] Received response 'textDocument/completion - (27)' in 1746ms.
[Trace - 1:24:29 PM] Received response 'textDocument/completion - (28)' in 1788ms.
[Trace - 1:24:29 PM] Sending notification '$/cancelRequest'.
[Trace - 1:24:29 PM] Sending request 'textDocument/signatureHelp - (47)'.
[Trace - 1:24:29 PM] Received response 'textDocument/completion - (29)' in 1801ms.
[Trace - 1:24:29 PM] Received response 'textDocument/completion - (30)' in 1803ms.
[Trace - 1:24:29 PM] Received response 'textDocument/completion - (31)' in 1817ms.
[Trace - 1:24:29 PM] Received response 'textDocument/codeAction - (33)' in 1827ms.
[Trace - 1:24:29 PM] Received response 'textDocument/documentSymbol - (5)' in 4066ms.
[Trace - 1:24:29 PM] Received response 'textDocument/signatureHelp - (34)' in 859ms.
[Trace - 1:24:29 PM] Received response 'textDocument/codeAction - (36)' in 869ms.
[Trace - 1:24:29 PM] Received response 'textDocument/signatureHelp - (37)' in 869ms.
[Trace - 1:24:29 PM] Sending notification 'textDocument/didChange'.
[Trace - 1:24:29 PM] Received response 'textDocument/signatureHelp - (38)' in 881ms.
[Trace - 1:24:29 PM] Received response 'textDocument/signatureHelp - (39)' in 801ms.
[Trace - 1:24:29 PM] Received response 'textDocument/signatureHelp - (40)' in 661ms.
[Trace - 1:24:29 PM] Received response 'textDocument/codeAction - (41)' in 494ms.
[Trace - 1:24:29 PM] Received response 'textDocument/signatureHelp - (43)' in 365ms.
[Trace - 1:24:29 PM] Received response 'textDocument/documentSymbol - (14)' in 2301ms.
[Trace - 1:24:29 PM] Received response 'textDocument/signatureHelp - (45)' in 241ms.
[Trace - 1:24:29 PM] Received response 'textDocument/completion - (46)' in 165ms.
[Trace - 1:24:29 PM] Received response 'textDocument/signatureHelp - (47)' in 107ms.
[Trace - 1:24:29 PM] Sending request 'textDocument/completion - (48)'.
[Trace - 1:24:29 PM] Sending request 'textDocument/signatureHelp - (49)'.
[Trace - 1:24:29 PM] Received response 'textDocument/completion - (48)' in 153ms.
[Trace - 1:24:29 PM] Received response 'textDocument/documentColor - (35)' in 1109ms.
[Trace - 1:24:29 PM] Received response 'textDocument/signatureHelp - (49)' in 95ms.
[Trace - 1:24:29 PM] Sending request 'completionItem/resolve - (50)'.
[Trace - 1:24:29 PM] Sending notification 'textDocument/didChange'.
[Trace - 1:24:29 PM] Sending request 'textDocument/completion - (51)'.
[Trace - 1:24:29 PM] Received response 'completionItem/resolve - (50)' in 23ms.
[Trace - 1:24:29 PM] Received response 'textDocument/completion - (51)' in 39ms.
[Trace - 1:24:30 PM] Sending request 'completionItem/resolve - (52)'.
[Trace - 1:24:30 PM] Sending notification 'textDocument/didChange'.
[Trace - 1:24:30 PM] Sending request 'textDocument/completion - (53)'.
[Trace - 1:24:30 PM] Received response 'completionItem/resolve - (52)' in 38ms.
[Trace - 1:24:30 PM] Received response 'textDocument/completion - (53)' in 49ms.
[Trace - 1:24:30 PM] Sending request 'completionItem/resolve - (54)'.
[Trace - 1:24:30 PM] Received response 'completionItem/resolve - (54)' in 33ms.
[Trace - 1:24:30 PM] Sending notification 'textDocument/didChange'.
[Trace - 1:24:30 PM] Sending request 'textDocument/completion - (55)'.
[Trace - 1:24:30 PM] Received response 'textDocument/completion - (55)' in 10ms.
[Trace - 1:24:30 PM] Sending request 'completionItem/resolve - (56)'.
[Trace - 1:24:30 PM] Received response 'completionItem/resolve - (56)' in 24ms.
[Trace - 1:24:30 PM] Received response 'textDocument/documentSymbol - (44)' in 1001ms.
[Trace - 1:24:30 PM] Sending request 'textDocument/codeAction - (57)'.
[Trace - 1:24:30 PM] Received response 'textDocument/codeAction - (57)' in 1ms.
[Trace - 1:24:30 PM] Sending request 'textDocument/documentSymbol - (58)'.
[Trace - 1:24:30 PM] Received response 'textDocument/documentColor - (2)' in 6400ms.
[Trace - 1:24:30 PM] Sending request 'textDocument/documentColor - (59)'.
[Trace - 1:24:30 PM] Sending request 'textDocument/codeAction - (60)'.
[Trace - 1:24:30 PM] Sending request 'textDocument/completion - (61)'.
[Trace - 1:24:30 PM] Received response 'textDocument/codeAction - (60)' in 1ms.
[Trace - 1:24:30 PM] Sending request 'textDocument/semanticTokens/range - (62)'.
Using Svelte v3.48.0 from /home/ubuntu/Work/DataBoss/web-v2/node_modules/svelte/compiler
Using Svelte v3.48.0 from /home/ubuntu/Work/DataBoss/web-v2/node_modules/svelte/compiler
[Trace - 1:24:30 PM] Received response 'textDocument/completion - (61)' in 99ms.
[Trace - 1:24:31 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 1:24:31 PM] Sending request 'completionItem/resolve - (63)'.
[Trace - 1:24:31 PM] Received response 'completionItem/resolve - (63)' in 6ms.
[Trace - 1:24:31 PM] Received response 'textDocument/documentSymbol - (32)' in 3429ms.
[Trace - 1:24:31 PM] Received response 'textDocument/documentColor - (42)' in 2002ms.
[Trace - 1:24:31 PM] Sending request 'textDocument/codeAction - (64)'.
[Trace - 1:24:31 PM] Received response 'textDocument/codeAction - (64)' in 4ms.
[Trace - 1:24:31 PM] Received response 'textDocument/documentSymbol - (58)' in 1003ms.
[Trace - 1:24:31 PM] Received response 'textDocument/semanticTokens/full - (6)' in 6299ms.
[Trace - 1:24:31 PM] Received response 'textDocument/documentColor - (59)' in 1009ms.
[Trace - 1:24:31 PM] Received response 'textDocument/semanticTokens/range - (62)' in 1086ms.
[Trace - 1:24:33 PM] Sending request 'textDocument/semanticTokens/full - (65)'.
[Trace - 1:24:34 PM] Received response 'textDocument/semanticTokens/full - (65)' in 1000ms.
[Trace - 1:25:38 PM] Sending notification '$/setTrace'.
[Trace - 1:25:39 PM] Sending request 'textDocument/semanticTokens/range - (66)'.
[Trace - 1:25:40 PM] Received response 'textDocument/semanticTokens/range - (66)' in 1002ms.
[Trace - 1:25:40 PM] Sending request 'textDocument/semanticTokens/full - (67)'.
[Trace - 1:25:40 PM] Sending notification '$/setTrace'.
[Trace - 1:25:41 PM] Sending request 'textDocument/semanticTokens/range - (68)'.
[Trace - 1:25:41 PM] Received response 'textDocument/semanticTokens/full - (67)' in 1000ms.
[Trace - 1:25:42 PM] Received response 'textDocument/semanticTokens/range - (68)' in 1001ms.
[Trace - 1:25:42 PM] Sending request 'textDocument/semanticTokens/full - (69)'.
[Trace - 1:25:43 PM] Received response 'textDocument/semanticTokens/full - (69)' in 1002ms.
[Trace - 1:25:44 PM] Sending notification '$/setTrace'.
[Trace - 1:25:44 PM] Sending request 'textDocument/semanticTokens/range - (70)'.
```

Let me know if there's more info I can provide.

**Comment by ambersnow** [comment]
I did some more comparing with my working project, a blank v260, another v259 project and this broken project. I actually ended up finding out what my problem was, I was missing the `jsconfig.json` file from my project root directory. Copied it over from the working project and the extension is now working like normal.

Maybe this is the same issue that @kwsope is having?

**Comment by jasonlyu123** [comment]
Closing due to inactivity and lack of reproduction. If you still experience this, please open a new issue with steps to reproduce.
