### ISSUE TITLE
Cannot read property 'tags' of null

### ISSUE THREAD

**Issue by easyfrog** [sveltejs/language-tools#1220]
```
[2021-10-29 00:13:04.152] [renderer5] [error] Cannot read property 'tags' of null: TypeError: Cannot read property 'tags' of null
	at asCompletionItem (/Users/easyfrog/.vscode/extensions/svelte.svelte-vscode-105.4.2/node_modules/vscode-languageclient/lib/common/protocolConverter.js:232:46)
	at Array.map (<anonymous>)
	at asCompletionResult (/Users/easyfrog/.vscode/extensions/svelte.svelte-vscode-105.4.2/node_modules/vscode-languageclient/lib/common/protocolConverter.js:202:51)
	at async U.provideCompletionItems (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:180703)
```

I use lastest version of `vscode`  and `Svelte for VS Code v105.4.2`

I got this error, when type code in script scope of svelte file.  I don't know where is wrong.

**Comment by dummdidumm** [comment]
I would be interested in finding out why it crashed without a tsconfig/jsconfig. If there's any minimum reproducible / reproduction repo you could share that would be great.
