### ISSUE TITLE
Prettier cannot format with Svelte Beta VS Code: Illegal argument: line must be non-negative

### ISSUE THREAD

**Issue by jzillmann** [sveltejs/language-tools#127]
**Describe the bug**
- I just switched [UnwrittenFun/svelte-vscode](https://marketplace.visualstudio.com/items?itemName=JamesBirtles.svelte-vscode) to Svelte Beta.
- Removed or disabled all other svelte VS code plugins
- Remove the html file association
- Typescript support is working
- Prettier stopped working for `.svelte` files
<img width="394" alt="Screen Shot 2020-05-28 at 17 55 52" src="https://user-images.githubusercontent.com/148472/83166082-ac446900-a10e-11ea-9b5d-7b619a8e7974.png">

In the `Log(Window)` i see this every time i save a touched svelte file (doesn't matter if `lang="typescript" or not`:
```
[2020-05-28 17:56:53.560] [renderer1] [error] Illegal argument: line must be non-negative: Error: Illegal argument: line must be non-negative
    at Object.t.illegalArgument (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:10:784)
    at new e (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:426:413)
    at new e (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:424:44)
    at asPosition (/Users/jz/.vscode/extensions/svelte.svelte-vscode-99.0.27/node_modules/vscode-languageclient/lib/protocolConverter.js:79:16)
    at asRange (/Users/jz/.vscode/extensions/svelte.svelte-vscode-99.0.27/node_modules/vscode-languageclient/lib/protocolConverter.js:85:31)
    at asSymbolInformation (/Users/jz/.vscode/extensions/svelte.svelte-vscode-99.0.27/node_modules/vscode-languageclient/lib/protocolConverter.js:449:85)
    at /Users/jz/.vscode/extensions/svelte.svelte-vscode-99.0.27/node_modules/vscode-languageclient/lib/protocolConverter.js:429:42
    at Array.map (<anonymous>)
    at Object.asSymbolInformations (/Users/jz/.vscode/extensions/svelte.svelte-vscode-99.0.27/node_modules/vscode-languageclient/lib/protocolConverter.js:429:23)
    at /Users/jz/.vscode/extensions/svelte.svelte-vscode-99.0.27/node_modules/vscode-languageclient/lib/client.js:1088:70
```

**To Reproduce**
- Happens on every svelte file for me
- I hope the exception is meaningful, haven't setup a small reproduction project yet

**Expected behavior**
- Prettier formatting should work

**System (please complete the following information):**
 - OS: OSX Mojave
 - IDE: VSCode 1.45.1
 - Plugin/Package: Svelte Beta 99.0.27
 - prettier: 2.0.5
 - prettier-plugin-svelte: 1.1.0

**Comment by dummdidumm** [comment]
The bug should be independent of whether or not you have `lang="typescript"` set.

Could you look at the log at Output -> Svelte and paste it in here?

**Comment by jzillmann** [comment]
```
loading config for /Users/jz/Documents/web/xxx/src/App.svelte
Using Svelte v3.23.0 from /Users/jz/Documents/web/xxx/node_modules/svelte/compiler
```

**Comment by dummdidumm** [comment]
This is the output if you try to format the file? If yes, that's strange because there should also be a message about loading prettier.

**Comment by jzillmann** [comment]
Yes, comes all the time i hit `save`. Actually the 2nd line comes 2 times. So 3 lines on every save.

**Comment by jzillmann** [comment]
Oh i think i found the problem. Had this in my VS Code `settings.json`:
```
 "[svelte]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  }
```
After i removed it, formatting started to work again!

The mentioned exception still happens though...

**Comment by dummdidumm** [comment]
I took a second look at it and it appears that the error you posted is unrelated to your problem. It happens because another method of the language server returns invalid line numbers - I will look into that. Thanks for bringing this to our attention.
