### ISSUE TITLE
MaxListenersExceededWarning: Possible EventEmitter memory leak detected.

### ISSUE THREAD

**Issue by hyrious** [sveltejs/language-tools#1418]
```
(node:13444) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:601:17)
    at EventEmitter.addListener (node:events:619:10)
    at GlobalSnapshotsManager.onChange (/Users/netless/hyrious/test/node_modules/svelte-check/dist/src/index.js:87960:22)
    at createLanguageService (/Users/netless/hyrious/test/node_modules/svelte-check/dist/src/index.js:88534:39)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

`node --trace-warnings` guides me here:

https://github.com/sveltejs/language-tools/blob/3f36b4777a3f4428f181f6938014faa047d81f38/packages/language-server/src/plugins/typescript/SnapshotManager.ts#L68-L70

Not sure whether it was false positive.

**Comment by dummdidumm** [comment]
I need more info about your project to know if this is a bug or not. Is this a monorepo with multiple projects? Is it reproducible (occurs reliably)? Does it occur when opening a specific file?

**Comment by hyrious** [comment]
The project is a monorepo managed by pnpm: https://github.com/netless-io/fastboard

I just run `svelte-check` at the root folder.
