### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'source')

### ISSUE THREAD

**Issue by KaRkY** [sveltejs/language-tools#1630]
### Describe the bug

When trying to autocomplete component properties I get this error:
```
TypeError: Cannot read properties of undefined (reading 'source')
    at CompletionsProviderImpl.getCompletions (c:\Users\e-svetinar\.vscode\extensions\svelte.svelte-vscode-105.22.1\node_modules\svelte-language-server\dist\src\plugins\typescript\features\CompletionProvider.js:136:34)
    at async TypeScriptPlugin.getCompletions (c:\Users\e-svetinar\.vscode\extensions\svelte.svelte-vscode-105.22.1\node_modules\svelte-language-server\dist\src\plugins\typescript\TypeScriptPlugin.js:137:29)
    at async PluginHost.tryExecutePlugin (c:\Users\e-svetinar\.vscode\extensions\svelte.svelte-vscode-105.22.1\node_modules\svelte-language-server\dist\src\plugins\PluginHost.js:300:20)
    at async c:\Users\e-svetinar\.vscode\extensions\svelte.svelte-vscode-105.22.1\node_modules\svelte-language-server\dist\src\plugins\PluginHost.js:55:28
    at async Promise.all (index 3)
    at async PluginHost.getCompletions (c:\Users\e-svetinar\.vscode\extensions\svelte.svelte-vscode-105.22.1\node_modules\svelte-language-server\dist\src\plugins\PluginHost.js:54:29)
```
As far as I could debug it I found that this pull https://github.com/sveltejs/language-tools/pull/1609 introduced this bug.
Error is happening in line https://github.com/sveltejs/language-tools/blob/0bffac8a27f6ae70cbfaebaa1e16b2dbec65b428/packages/language-server/src/plugins/typescript/features/CompletionProvider.ts#L274

### Reproduction

I am using "carbon-components-svelte" maybe this is the problem since it works OK with my own components.

I created a github repo which if you try to autocomplete inside +page.svelte on a Header component there should be an error in output but if you try to autocomplete inside Component it's OK.

https://github.com/KaRkY/svelte-vscode-reproduction

### Expected behaviour

Autocomplete should actually suggest useful suggestions.

### System Info

- Windows
-  VSCode (1.71.0)
- Svelte extension (105.22.1 or 105.22.0) It works OK in 105.21.0

### Which package is the issue about?

svelte-language-server

**Comment by dummdidumm** [comment]
Thank you for the detailed reproduction! Fix is underway

**Comment by KaRkY** [comment]
I just saw the release and now it works thanks.
