### ISSUE TITLE
Language server keeps crashing on VSCode

### ISSUE THREAD

**Issue by kwangure** [sveltejs/language-tools#179]
**Describe the bug**
The Svelte language server on my machine has crashed a few times today. The crashes seem random (i.e I've been unable reproduce them using a predictable action/trigger).

Since this started, Emmet autocompletion seems to have stopped working (i.e `div.my-class` no longer offers the autocompletion `<div class="my-class">|</div>`), though this may be a separate and unrelated issue.

**Screenshots**
![Screenshot 2020-06-09 at 1 41 24 pm](https://user-images.githubusercontent.com/20745107/84139236-2f8f8400-aa58-11ea-8df6-9dc709753f7b.png)

**System (please complete the following information):**
 - OS: [e.g. MacOS Catalina]
 - IDE: [e.g. VSCode]
 - Plugin/Package: [e.g. "Svelte Beta"]

**Additional Context**
I only have a few files (25-ish), and I'm not using Sapper. It persists even when all extensions but Svelte-Beta are disabled. The `output` section of the VSCode blanks out with no logs when the server crashes.

I'll update this issue with *SOME* actionable information if I found out more, but feel free to close this if myself or others are unable to reliably reproduce this. In the meantime, suggestions?

**Comment by sw-yx** [comment]
would be nice to see the error stack of where exactly it crashed. i think theres a vscode panel where you can get that info?

**Comment by dummdidumm** [comment]
It's Output->Svelte, but reading the issue it seems @kwangure already looked there.

**Comment by sw-yx** [comment]
based on a quick google of other issues

- https://www.codeproject.com/Tips/5163886/Fixing-VS-Code-Extension-Errors
- https://github.com/Microsoft/vscode-cpptools/issues/1302
- https://github.com/redhat-developer/vscode-java/issues/828

it seems this could be due to corrupted vscode/etensions. might need to delete and reinstall everything.

>   If your plug-in is acting weirdly or crashing, consider deleting the extension directory from your system from the .vscode folder located in your home directory.

**Comment by devrnt** [comment]
Had the same issue yesterday, seems to be fixed in the latest release. 

Make sure to manually remove your extension in your directory and reinstall the extension. You can find the extension here: `C:\Users\[user]\.vscode\extensions`

**Comment by rob-balfre** [comment]
Kills my sapper project

```<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x112b22899]
    1: StubFrame [pc: 0x112acda5f]
Security context: 0x11d690660dd1 <JSObject>
    2: parseObjectLiteralExpression(aka parseObjectLiteralExpression) [0x11d673c37ef9] [/Users/../.vscode/extensions/svelte.svelte-vscode-99.0.41/node_modules/typescript/lib/typescript.js:~23516] [pc=0x1e769dc268b1](this=0x11d6333804b1 <undefined>)
    3: parsePrimaryExpression(aka parsePrimaryExpression) [0x11d673c3...

[Info  - 4:32:04 PM] Connection to server got closed. Server will restart.
[Error - 4:32:04 PM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (/Users/../.vscode/extensions/svelte.svelte-vscode-99.0.41/node_modules/vscode-jsonrpc/lib/main.js:904:25)
	at Object.dispose (/Users/../.vscode/extensions/svelte.svelte-vscode-99.0.41/node_modules/vscode-languageclient/lib/client.js:74:35)
	at LanguageClient.handleConnectionClosed (/Users/../.vscode/extensions/svelte.svelte-vscode-99.0.41/node_modules/vscode-languageclient/lib/client.js:2309:42)
	at LanguageClient.handleConnectionClosed (/Users/../.vscode/extensions/svelte.svelte-vscode-99.0.41/node_modules/vscode-languageclient/lib/main.js:155:15)
	at closeHandler (/Users/../.vscode/extensions/svelte.svelte-vscode-99.0.41/node_modules/vscode-languageclient/lib/client.js:2296:18)
	at CallbackList.invoke (/Users/../.vscode/extensions/svelte.svelte-vscode-99.0.41/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/Users/../.vscode/extensions/svelte.svelte-vscode-99.0.41/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at closeHandler (/Users/../.vscode/extensions/svelte.svelte-vscode-99.0.41/node_modules/vscode-jsonrpc/lib/main.js:240:26)
	at CallbackList.invoke (/Users/../.vscode/extensions/svelte.svelte-vscode-99.0.41/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/Users/../.vscode/extensions/svelte.svelte-vscode-99.0.41/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at IPCMessageReader.fireClose (/Users/../.vscode/extensions/svelte.svelte-vscode-99.0.41/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
	at ChildProcess.<anonymous> (/Users/../.vscode/extensions/svelte.svelte-vscode-99.0.41/node_modules/vscode-jsonrpc/lib/messageReader.js:213:45)
	at ChildProcess.emit (events.js:208:15)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
[Error - 4:32:04 PM] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/Users/../.vscode/extensions/svelte.svelte-vscode-99.0.41/node_modules/vscode-jsonrpc/lib/main.js:904:25)
	at Object.dispose (/Users/../.vscode/extensions/svelte.svelte-vscode-99.0.41/node_modules/vscode-languageclient/lib/client.js:74:35)
	at LanguageClient.handleConnectionClosed (/Users/../.vscode/extensions/svelte.svelte-vscode-99.0.41/node_modules/vscode-languageclient/lib/client.js:2309:42)
	at LanguageClient.handleConnectionClosed (/Users/../.vscode/extensions/svelte.svelte-vscode-99.0.41/node_modules/vscode-languageclient/lib/main.js:155:15)
	at closeHandler (/Users/../.vscode/extensions/svelte.svelte-vscode-99.0.41/node_modules/vscode-languageclient/lib/client.js:2296:18)
	at CallbackList.invoke (/Users/../.vscode/extensions/svelte.svelte-vscode-99.0.41/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/Users/../.vscode/extensions/svelte.svelte-vscode-99.0.41/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at closeHandler (/Users/../.vscode/extensions/svelte.svelte-vscode-99.0.41/node_modules/vscode-jsonrpc/lib/main.js:240:26)
	at CallbackList.invoke (/Users/../.vscode/extensions/svelte.svelte-vscode-99.0.41/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/Users/../.vscode/extensions/svelte.svelte-vscode-99.0.41/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at IPCMessageReader.fireClose (/Users/../.vscode/extensions/svelte.svelte-vscode-99.0.41/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
	at ChildProcess.<anonymous> (/Users/../.vscode/extensions/svelte.svelte-vscode-99.0.41/node_modules/vscode-jsonrpc/lib/messageReader.js:213:45)
	at ChildProcess.emit (events.js:208:15)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
Initialize language server at  /Users/../flex
Initialize new ts service at  
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x107c51245 node::Abort() [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 2: 0x107c512b4 node::Abort() [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 3: 0x10395f1b7 v8::internal::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 4: 0x10395f157 v8::internal::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 5: 0x1039a4025 v8::internal::Heap::StartIdleIncrementalMarking(v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 6: 0x1039a5699 v8::internal::Heap::StartIdleIncrementalMarking(v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 7: 0x1039a236c v8::internal::Heap::CreateFillerObjectAt(unsigned long, int, v8::internal::ClearRecordedSlots, v8::internal::ClearFreedMemoryMode) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 8: 0x10399ff82 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 9: 0x1039ab3ea v8::internal::Heap::PromotedExternalMemorySize() [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
10: 0x1039ab7d1 v8::internal::Heap::PromotedExternalMemorySize() [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
11: 0x103bac9da v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
12: 0x103e3581f v8::internal::RegExp::CompileForTesting(v8::internal::Isolate*, v8::internal::Zone*, v8::internal::RegExpCompileData*, v8::base::Flags<v8::internal::JSRegExp::Flag, int>, v8::internal::Handle<v8::internal::String>, v8::internal::Handle<v8::internal::String>, bool) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
13: 0x104477899 v8::internal::compiler::ZoneStats::ReturnZone(v8::internal::Zone*) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]

<--- Last few GCs --->
oc[58080:0x1099ec000]    47061 ms: Mark-sweep 4096.1 (4103.8) -> 4095.6 (4104.0) MB, 2115.2 / 0.0 ms  (+ 89.2 ms in 18 steps since start of marking, biggest step 8.3 ms, walltime since start of marking 2212 ms) (average mu = 0.086, current mu = 0.003) alloc[58080:0x1099ec000]    49299 ms: Mark-sweep 4097.0 (4104.3) -> 4096.6 (4105.0) MB, 2212.8 / 0.0 ms  (+ 14.6 ms in 22 steps since start of marking, biggest step 11.0 ms, walltime since start of marking 2237 ms) (average mu = 0.044, current mu = 0.004) allo
```

**Comment by dummdidumm** [comment]
The Sapper memory leak is discussed in #151 . We pushed a fix for it, should be available tomorrow.

**Comment by kwangure** [comment]
Upgrading to the latest version of Svelte-Beta solved my Emmet and crashing woes. Closing this now.
