### ISSUE TITLE
Svelte Language Server Crashes on Startup of VSCode (WSL)

### ISSUE THREAD

**Issue by david-bergman** [sveltejs/language-tools#1848]
### Describe the bug

On opening VsCode, the language server crashes

The Svelte server crashed 5 times in the last 3 minutes. The server will not be restarted.

Upon looking at the output logs

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/davidb/.vscode-server/extensions/svelte.svelte-vscode-106.4.1/node_modules/vscode-jsonrpc/lib/common/api.js:37:21)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
[Info  - 8:16:37 PM] Connection to server got closed. Server will restart.
/home/davidb/.vscode-server/extensions/svelte.svelte-vscode-106.4.1/node_modules/vscode-jsonrpc/lib/common/linkedMap.js:40
        return this._head?.value;
                          ^

### Reproduction

svelte.svelte-vscode-106.4.1
VsCode 1.55.2

### Expected behaviour

I am expecting the Svelte Server to work with VsCode (WSL) without crashing. 

### System Info

- OS: Windows (WSL)
- IDE: VSCode

### Which package is the issue about?

svelte-language-server

**Comment by jasonlyu123** [comment]
We ship the wrong version of the language server in `106.4.1` which requires a newer version of node.js. It should work if you update to VSCode 1.67 or later. Let's see if we can fix the old major release.

**Comment by david-bergman** [comment]
works for me with the upgrade of VSCode, thanks !

**Comment by jasonlyu123** [comment]
Closing because not too many people run into this. And the required VSCode 1.67 has also been released for nearly 2 years.
