### ISSUE TITLE
SemanticTokensRefresh & InlayHintRefresh are unsupported by Neovim

### ISSUE THREAD

**Issue by aidenlangley** [sveltejs/language-tools#1895]
### Describe the bug

I believe `workspace/SemanticTokens/refresh` & `workspace/inlayHints/refresh` requests made to Neovim are causing the server to crash, since the client doesn't support these operations.

My setup is to have `svelte-language-server` running in `.svelte` buffers, but `tsserver` in `.ts` buffers. Saving, or doing just about anything, in a `typescript` file is causing the `svelte-language-server` to send the requests I mentioned, so it can provide an update on the diagnostics state to the client.

It should perhaps be configurable - none of the options provided disable this functionality.

### Reproduction

A Neovim setup using with the default svelte and typescript config will suffice.

1. Edit a `svelte` file to start up the `svelte-language-server`.
2. Edit a `typescript` file to start up `tsserver`.
3. `svelte-language-server` will crash with the following output to `.local/state/nvim/lsp.log` or equivalent on another OS:

```config
[WARN][2023-02-24 01:06:28] .../lua/vim/lsp.lua:1065	"server_request: no handler found for"	"workspace/inlayHint/refresh"
[WARN][2023-02-24 01:06:28] .../lua/vim/lsp.lua:1065	"server_request: no handler found for"	"workspace/semanticTokens/refresh"
[ERROR][2023-02-24 01:06:28] .../vim/lsp/rpc.lua:733	"rpc"	"svelteserver"	"stderr"	"/home/aiden/.local/share/nvim/mason/packages/svelte-language-server/node_modules/svelte-language-server/node_modules/vscode-jsonrpc/lib/common/connection.js:531\n                        responsePromise.reject(new messages_1.ResponseError(error.code, error.message, error.data));\n                                               ^\n\nResponseError: MethodNotFound\n    at handleResponse (/home/aiden/.local/share/nvim/mason/packages/svelte-language-server/node_modules/svelte-language-server/node_modules/vscode-jsonrpc/lib/common/connection.js:531:48)\n    at processMessageQueue (/home/aiden/.local/share/nvim/mason/packages/svelte-language-server/node_modules/svelte-language-server/node_modules/vscode-jsonrpc/lib/common/connection.js:327:17)\n    at Immediate.<anonymous> (/home/aiden/.local/share/nvim/mason/packages/svelte-language-server/node_modules/svelte-language-server/node_modules/vscode-jsonrpc/lib/common/connection.js:311:13)\n    at processImmediate (node:internal/timers:466:21) {\n  code: -32601,\n  data: undefined\n}\n"
```

### Expected behaviour

Would like to be able to switch these requests off.

### System Info

- OS: Linux
- IDE: Neovim v0.8.3

### Which package is the issue about?

svelte-language-server

**Comment by aidenlangley** [comment]
Here is a workaround in case anyone is interested:

`svelte` `lspconfig` table:
```lua
settings = {
  initializationOptions = {
    configuration = {
      svelte = {
        plugin = {
          typescript = { semanticTokens = { enable = false } },
        },
      },
    },
    preferences = {
      includeInlayEnumMemberValueHints = false,
      includeInlayFunctionParameterTypeHints = false,
      includeInlayFunctionLikeReturnTypeHints = false,
      includeInlayParameterNameHints = "none",
      includeInlayParameterNameHintsWhenArgumentMatchesName = false,
      includeInlayPropertyDeclarationTypeHints = false,
      includeInlayVariableTypeHints = false,
      includeInlayVariableTypeHintsWhenTypeMatchesName = false,
    },
  },
},
```

`tsserver` `lspconfig` table:
```lua
filetypes = {
          "javascript",
          "javascriptreact",
          "javascript.jsx",
          "svelte",
          "typescript",
          "typescriptreact",
          "typescript.tsx",
        },
        settings = {
          initializationOptions = {
            preferences = {
              includeInlayEnumMemberValueHints = false,
              includeInlayFunctionParameterTypeHints = false,
              includeInlayFunctionLikeReturnTypeHints = false,
              includeInlayParameterNameHints = "none",
              includeInlayParameterNameHintsWhenArgumentMatchesName = false,
              includeInlayPropertyDeclarationTypeHints = false,
              includeInlayVariableTypeHints = false,
              includeInlayVariableTypeHintsWhenTypeMatchesName = false,
            },
          },
        },
```

**Comment by aidenlangley** [comment]
And I suppose that proves it is configurable lol. Workaround was tricky to put together because `tsserver` is a bit of a pain to configure, but it's doable. Can probably just close?
