### ISSUE TITLE
Formatter not working properly

### ISSUE THREAD

**Issue by lucassilvas1** [sveltejs/language-tools#1946]
### Describe the bug

The Svelte for VS Code extension suddenly stopped formatting `.svelte` files that have `script` or `style` tags.

I get this as the output for Svelte when I try to format the document:
```
{
    "type": "Style",
    "start": 170,
    "end": 215,
    "attributes": [
        {
            "start": 177,
            "end": 206,
            "type": "Attribute",
            "name": "✂prettier:content✂",
            "value": [
                {
                    "start": 197,
                    "end": 205,
                    "type": "Text",
                    "raw": "CgogIAo=",
                    "data": "CgogIAo="
                }
            ]
        }
    ],
    "children": [],
    "content": {
        "start": 207,
        "end": 207,
        "styles": "",
        "type": "StyleProgram"
    }
}
Error: unknown node type: Style
    at Object.print (c:\Users\Lucas\.vscode\extensions\svelte.svelte-vscode-107.2.5\node_modules\prettier-plugin-svelte\plugin.js:1432:11)
    at callPluginPrintFunction (c:\Users\Lucas\.vscode\extensions\svelte.svelte-vscode-107.2.5\node_modules\prettier\index.js:8417:26)
    at mainPrintInternal (c:\Users\Lucas\.vscode\extensions\svelte.svelte-vscode-107.2.5\node_modules\prettier\index.js:8366:22)
    at mainPrint (c:\Users\Lucas\.vscode\extensions\svelte.svelte-vscode-107.2.5\node_modules\prettier\index.js:8353:18)
    at AstPath.call (c:\Users\Lucas\.vscode\extensions\svelte.svelte-vscode-107.2.5\node_modules\prettier\index.js:8175:24)
    at printTopLevelParts (c:\Users\Lucas\.vscode\extensions\svelte.svelte-vscode-107.2.5\node_modules\prettier-plugin-svelte\plugin.js:1483:32)
    at Object.print (c:\Users\Lucas\.vscode\extensions\svelte.svelte-vscode-107.2.5\node_modules\prettier-plugin-svelte\plugin.js:888:16)
    at callPluginPrintFunction (c:\Users\Lucas\.vscode\extensions\svelte.svelte-vscode-107.2.5\node_modules\prettier\index.js:8417:26)
    at mainPrintInternal (c:\Users\Lucas\.vscode\extensions\svelte.svelte-vscode-107.2.5\node_modules\prettier\index.js:8366:22)
    at mainPrint (c:\Users\Lucas\.vscode\extensions\svelte.svelte-vscode-107.2.5\node_modules\prettier\index.js:8353:18)

```

Removing all `script` and `style` tags from the file solves it.
I've tried several different versions of the Svelte for VS Code and Prettier extensions, I always get that same error.

**P.S.:**
I have Svelte for VS Code set as the formatter in `settings.json`
![image](https://user-images.githubusercontent.com/52336985/226210209-43cd12e9-c70b-44b9-aeef-92028e975104.png)

### Reproduction

1. Install Prettier v9.10.4;
2. Install Svelte for VS Code v107.2.5;
3. Create a simple `.svelte` file, e.g.
 ```
<script><script>

<div><div>
```
4. Format the code, either by saving or right-clicking.

### Expected behaviour

Document is formatted.

### System Info

- OS: Windows 10
- IDE: VS Code v1.76.2

### Which package is the issue about?

Svelte for VS Code extension

**Comment by ixxie** [comment]
I am running into the same issue after updating my system this week, except I don't see any error messages (but then again, maybe I don't know where to look).

**Comment by lucassilvas1** [comment]
> I am running into the same issue after updating my system this week, except I don't see any error messages (but then again, maybe I don't know where to look).

Look at the output in the console
![image](https://user-images.githubusercontent.com/52336985/226391289-fc448103-b511-412e-a1a0-fa79a05422ed.png)

**Comment by ixxie** [comment]
Aha, I tried before but didn't realize about #2 and #3. Thanks.

It seems I may be having a different issue after all:

```
SnapshotManager File Statistics:
Project files: 55
Svelte files: 27
From node_modules: 678
Total: 735
Error: Cannot find module 'prettier-plugin-svelte'
Require stack:
- /home/ixxie/repos/shenhav.fyi/node_modules/prettier/index.js
- /nix/store/xy253zza1rq6wsxwr63b8zg4g7fp0xgd-vscode-extension-svelte-svelte-vscode-106.3.0/share/vscode/extensions/svelte.svelte-vscode/node_modules/svelte-language-server/dist/src/importPackage.js
- /nix/store/xy253zza1rq6wsxwr63b8zg4g7fp0xgd-vscode-extension-svelte-svelte-vscode-106.3.0/share/vscode/extensions/svelte.svelte-vscode/node_modules/svelte-language-server/dist/src/lib/documents/configLoader.js
- /nix/store/xy253zza1rq6wsxwr63b8zg4g7fp0xgd-vscode-extension-svelte-svelte-vscode-106.3.0/share/vscode/extensions/svelte.svelte-vscode/node_modules/svelte-language-server/dist/src/lib/documents/Document.js
- /nix/store/xy253zza1rq6wsxwr63b8zg4g7fp0xgd-vscode-extension-svelte-svelte-vscode-106.3.0/share/vscode/extensions/svelte.svelte-vscode/node_modules/svelte-language-server/dist/src/lib/documents/index.js
- /nix/store/xy253zza1rq6wsxwr63b8zg4g7fp0xgd-vscode-extension-svelte-svelte-vscode-106.3.0/share/vscode/extensions/svelte.svelte-vscode/node_modules/svelte-language-server/dist/src/server.js
- /nix/store/xy253zza1rq6wsxwr63b8zg4g7fp0xgd-vscode-extension-svelte-svelte-vscode-106.3.0/share/vscode/extensions/svelte.svelte-vscode/node_modules/svelte-language-server/bin/server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at resolve (node:internal/modules/cjs/helpers:108:19)
    at /home/ixxie/repos/shenhav.fyi/node_modules/prettier/index.js:38105:25
    at Array.map (<anonymous>)
    at Object.load (/home/ixxie/repos/shenhav.fyi/node_modules/prettier/index.js:38100:65)
    at Object.load [as loadPlugins] (/home/ixxie/repos/shenhav.fyi/node_modules/prettier/index.js:16147:23)
    at /home/ixxie/repos/shenhav.fyi/node_modules/prettier/index.js:38167:24
    at Object.format (/home/ixxie/repos/shenhav.fyi/node_modules/prettier/index.js:38183:12)
    at SveltePlugin.formatDocument (/nix/store/xy253zza1rq6wsxwr63b8zg4g7fp0xgd-vscode-extension-svelte-svelte-vscode-106.3.0/share/vscode/extensions/svelte.svelte-vscode/node_modules/svelte-language-server/dist/src/plugins/svelte/SveltePlugin.js:66:40)
    at async PluginHost.tryExecutePlugin (/nix/store/xy253zza1rq6wsxwr63b8zg4g7fp0xgd-vscode-extension-svelte-svelte-vscode-106.3.0/share/vscode/extensions/svelte.svelte-vscode/node_modules/svelte-language-server/dist/src/plugins/PluginHost.js:321:20) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/ixxie/repos/shenhav.fyi/node_modules/prettier/index.js',
    '/nix/store/xy253zza1rq6wsxwr63b8zg4g7fp0xgd-vscode-extension-svelte-svelte-vscode-106.3.0/share/vscode/extensions/svelte.svelte-vscode/node_modules/svelte-language-server/dist/src/importPackage.js',
    '/nix/store/xy253zza1rq6wsxwr63b8zg4g7fp0xgd-vscode-extension-svelte-svelte-vscode-106.3.0/share/vscode/extensions/svelte.svelte-vscode/node_modules/svelte-language-server/dist/src/lib/documents/configLoader.js',
    '/nix/store/xy253zza1rq6wsxwr63b8zg4g7fp0xgd-vscode-extension-svelte-svelte-vscode-106.3.0/share/vscode/extensions/svelte.svelte-vscode/node_modules/svelte-language-server/dist/src/lib/documents/Document.js',
    '/nix/store/xy253zza1rq6wsxwr63b8zg4g7fp0xgd-vscode-extension-svelte-svelte-vscode-106.3.0/share/vscode/extensions/svelte.svelte-vscode/node_modules/svelte-language-server/dist/src/lib/documents/index.js',
    '/nix/store/xy253zza1rq6wsxwr63b8zg4g7fp0xgd-vscode-extension-svelte-svelte-vscode-106.3.0/share/vscode/extensions/svelte.svelte-vscode/node_modules/svelte-language-server/dist/src/server.js',
    '/nix/store/xy253zza1rq6wsxwr63b8zg4g7fp0xgd-vscode-extension-svelte-svelte-vscode-106.3.0/share/vscode/extensions/svelte.svelte-vscode/node_modules/svelte-language-server/bin/server.js'
  ]
}
```

**Comment by jasonlyu123** [comment]
@ixxie That is unrelated. It's probably a fixed issue https://github.com/sveltejs/language-tools/issues/1766. Your extension needs to be updated. Please update VSCode and your extension to the latest version. If the problem persists, open another issue. 

@lucassilvas1 Please provide a reproduction repository. We would like more info to investigate.

**Comment by lucassilvas1** [comment]
> @lucassilvas1 Please provide a reproduction repository. We would like more info to investigate.

Here it is https://github.com/lucassilvas1/svelte-formatter-bug-mre

Just clone it, install dependencies and try to format `App.svelte`. For me it doesn't work.

**Comment by jasonlyu123** [comment]
Guess it's something specific to your environment. I tried reproducing it with the snippet in a new svelte kit project and your repository. Both work fine for me. Can you check if you have any user config related to `svelte.plugin.svelte.format` or any [prettier config files](https://prettier.io/docs/en/configuration.html) outside of your workspace?

**Comment by lucassilvas1** [comment]
> Can you check if you have any user config related to `svelte.plugin.svelte.format`
Where would I check that? I have never created a `.prettierrc` file, so I don't think so.

> or any [prettier config files](https://prettier.io/docs/en/configuration.html) outside of your workspace?
Would erasing the `settings.json` file temporarily do the trick?

**Comment by lucassilvas1** [comment]
Erasing `settings.json` did the trick.

Could you maybe give a quick look at my `settings.json` file and see if anything seems off? It's weird that it stopped working out of nowhere when it worked just fine for several months.

```json
{
  "[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[html]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[svelte]": {
    "editor.defaultFormatter": "svelte.svelte-vscode"
  },
  "liveServer.settings.donotVerifyTags": true,
  "editor.formatOnPaste": true,
  "highlight-matching-tag.styles": {
    "opening": {
      "left": {
        "custom": {
          "borderWidth": "0 0 0 1px",
          "borderStyle": "solid",
          "borderColor": "yellow",
          "borderRadius": "5px",
          "overviewRulerColor": "white"
        }
      },
      "right": {
        "custom": {
          "borderWidth": "0 1px 0 0",
          "borderStyle": "solid",
          "borderColor": "yellow",
          "borderRadius": "5px",
          "overviewRulerColor": "white"
        }
      }
    }
  },
  "editor.tabSize": 2,
  "editor.glyphMargin": false,
  "explorer.confirmDelete": false,
  "liveServer.settings.donotShowInfoMsg": true,
  "editor.bracketPairColorization.enabled": true,
  "editor.guides.bracketPairs": true,
  "editor.fontFamily": "'Iosevka', 'Envy Code R','Hack NF', Consolas, 'Courier New', monospace",
  "terminal.integrated.scrollback": 30000,
  "javascript.updateImportsOnFileMove.enabled": "always",
  "editor.fontLigatures": true,
  "editor.minimap.enabled": false,
  "workbench.colorCustomizations": {
    "[Vitesse Dark]": {
      "editor.wordHighlightBackground": "#202020",
      "editor.wordHighlightStrongBackground": "#202020",
      "editor.wordHighlightBorder": "#696969",
      "editor.selectionHighlightBorder": "#696969"
    }
  },
  "svelte.plugin.svelte.note-new-transformation": false,
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "editor.formatOnSave": true,
  "editor.mouseWheelZoom": true,
  "workbench.colorTheme": "GitHub Dark Default",
  "typescript.updateImportsOnFileMove.enabled": "always",
  "svelte.enable-ts-plugin": true,
  "prettier.embeddedLanguageFormatting": "off",
  "settingsSync.ignoredSettings": [
    
  ]
}

```

**Comment by jasonlyu123** [comment]
Seems like "prettier.embeddedLanguageFormatting": "off" is the problem.

**Comment by lucassilvas1** [comment]
> Seems like "prettier.embeddedLanguageFormatting": "off" is the problem.

It is, was about to comment that. Thank you for your help.
