### ISSUE TITLE
Svelte Server crashed 5 times in the last 3 minutes

### ISSUE THREAD

**Issue by BigBoulard** [sveltejs/language-tools#2040]
Hi guys,

I have a problem currently. Svelte doesn't work as expected in VSCode: no automatic indentation on save, formatting, emmet, svelte snippets etc.

Here's the VSCode output:

```sh
SyntaxError: Unexpected token '||='
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/Users/me/.vscode/extensions/svelte.svelte-vscode-107.5.1/node_modules/svelte-language-server/dist/src/plugins/typescript/features/CodeActionsProvider.js:11:28)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[Error - 15:38:13] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 15:38:13] Connection to server got closed. Server will restart.
true
[Error - 15:38:13] Svelte client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 15:38:13] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
/Users/me/.vscode/extensions/svelte.svelte-vscode-107.5.1/node_modules/svelte-language-server/dist/src/plugins/typescript/DocumentSnapshot.js:411
                this.paramsPath ||= files.params;
                                ^^^

SyntaxError: Unexpected token '||='
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/Users/me/.vscode/extensions/svelte.svelte-vscode-107.5.1/node_modules/svelte-language-server/dist/src/plugins/typescript/features/CodeActionsProvider.js:11:28)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[Error - 15:38:16] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 15:38:16] The Svelte server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 15:38:16] Svelte client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 15:38:16] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
```

Thank you

**Comment by gtm-nayan** [comment]
vscode still ships with node 14 iirc, I think it stopped downleveling the `||=` because of these changes https://github.com/sveltejs/language-tools/pull/2027/files#diff-d11996e40a95bacab295938bd0c093d6c8ca28597a53b9c5536d703e5eb7fd2bR2

**Comment by dummdidumm** [comment]
Vs code ships with node 16 at this point, and it's the minimum required version for the language server. Are you using an old version of vs code or did you set the node runtime manually?

**Comment by BigBoulard** [comment]
Here's the conf

```sh
Version: 1.78.2
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:44:45.204Z (3 wks ago)
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 22.3.0
Sandboxed: No
```

**Comment by jasonlyu123** [comment]
Do you have the `svelte.language-server.runtime` config? You might be using nvm, Volta or something similar. And the config points to another install that is not the version you see in the terminal.

**Comment by jasonlyu123** [comment]
Have you checked if `/usr/local/bin/node` still shows node 14? Not sure about Mac. But if I use nvm to install node in ubuntu, `which node` suggests the node command is from `~/.nvm/v18.16.0/bin/node`. Maybe that's installed by the installer instead of `nvm`?

**Comment by BigBoulard** [comment]
```sh
> which node
/Users/me/.nvm/versions/node/v18.16.0/bin/node

> which npm
/Users/me/.nvm/versions/node/v18.16.0/bin/npm

> which pnpm
/Users/me/.nvm/versions/node/v18.16.0/bin/pnpm

> node -v
v18.16.0

> /usr/local/bin/node
Welcome to Node.js v14.18.0.
Type ".help" for more information.
```

I tried to remove the files from the previous install (probably done through the installer I guess <https://nodejs.org/en/download>)
```sh
> rm -rf /usr/local/bin/node
> sudo rm -rf /usr/local/lib/dtrace/node.d
> rm -rf ~/.npm
```

I can see `NODE_PATH` and `NODE_ENV` in VSCode settings but I'm not sure its relevant here.

**Comment by gtm-nayan** [comment]
If you have a path to a binary set explicitly then it'll always use the executable at that path instead of what "which node" gives you. If NODE_PATH is set to /usr/local/bin/node, removing it could work.

**Comment by jasonlyu123** [comment]
The `svelte.language-server.runtime` config is very simple. It doesn't care how your node.js should be in your system. If you set a path to that config, it will use that path to launch. So you need to update the "/usr/local/bin/node" to a different path or leave it empty. Removing the files there won't stop the crash.

**Comment by BigBoulard** [comment]
`NODE_PATH` and `NODE_ENV` were empty. Didn't know about `svelte.language-server.runtime` which was pointing to the old node install from the installer (`svelte.language-server.runtime`). I just removed the reference and it's working now. Thank you all for your time and patience, appreciate it 👍
