### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'some')

### ISSUE THREAD

**Issue by Antoine-lb** [sveltejs/language-tools#2090]
### Describe the bug

Fails to format because of error:

```js
TypeError: Cannot read properties of undefined (reading 'some')
  at getSveltePlugin (/Users/me/.vscode/extensions/svelte.svelte-vscode-107.7.0/node_modules/svelte-language-server/dist/src/plugins/svelte/SveltePlugin.js:89:27)
  at SveltePlugin.formatDocument (/Users/me/.vscode/extensions/svelte.svelte-vscode-107.7.0/node_modules/svelte-language-server/dist/src/plugins/svelte/SveltePlugin.js:73:20)
  at async PluginHost.tryExecutePlugin (/Users/me/.vscode/extensions/svelte.svelte-vscode-107.7.0/node_modules/svelte-language-server/dist/src/plugins/PluginHost.js:342:20)
  at async Promise.all (index 0)
  at async PluginHost.execute (/Users/me/.vscode/extensions/svelte.svelte-vscode-107.7.0/node_modules/svelte-language-server/dist/src/plugins/PluginHost.js:319:24)
  at async PluginHost.formatDocument (/Users/me/.vscode/extensions/svelte.svelte-vscode-107.7.0/node_modules/svelte-language-server/dist/src/plugins/PluginHost.js:114:38)
```

Reading your code base it seems that it comes from this function:
```js
function getSveltePlugin() {
    // Only provide our version of the svelte plugin if the user doesn't have one in
    // the workspace already. If we did it, Prettier would - for some reason - use
    // the workspace version for parsing and the extension version for printing,
    // which could crash if the contract of the parser output changed.
    const hasPluginLoadedAlready = prettier
        .getSupportInfo()
        .languages.some((l) => l.name === 'svelte'); // ERROR: .lenguages is undefined
    return hasPluginLoadedAlready ? [] : [require.resolve('prettier-plugin-svelte')];
}
```

### Reproduction

1. Install brand new installation of VS Code
2. Install "Svelte for VS Code"
3. Add format on save and default formatter for Svelte
4. Try saving but doesn't work

(to try more stuff)
5. Install Prettier
6. Saving doesn't work
7. Configure on save and stuff
8. Still doesn't work

My final VS Code settings:
```json
{
  "svelte.enable-ts-plugin": true,
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "editor.formatOnSave": true,
  "[svelte]": {
    "editor.formatOnSave": true,
    "editor.defaultFormatter": "svelte.svelte-vscode"
  }
}

```

### Expected behaviour

It formats Svelte code on save

### System Info

- OS: MacOS Ventura 13.3.1 (a) 
- IDE: VSCode 1.80.0 (Universal)

### Which package is the issue about?

Svelte for VS Code `v107.7.0`

**Comment by dummdidumm** [comment]
Is Prettier 3.x in there somewhere? Through the Prettier extension or through the project you run this within?

**Comment by feugy** [comment]
For information @Antoine-lb, I got the same issue, and fixed it by migrating to:
- prettier@3.0.0
- prettier-plugin-svelte@3.0.3
- Svelte for VS Code plugin@107.9.0

**Comment by Antoine-lb** [comment]
@feugy like dummdidumm said, is better not tu use prettier 3.x for now, is not supported yet

**Comment by dummdidumm** [comment]
It's supported in the latest version of the vs code extension now, but you need to install the fitting prettier and svelte plugin version yourself
