### ISSUE TITLE
Issue with Svelte Language Server in NeoVim

### ISSUE THREAD

**Issue by chrishumboldt** [sveltejs/language-tools#2102]
### Describe the bug

My svelte language server keeps crashing with the following error output:

[ERROR][2023-07-20 09:20:23] .../vim/lsp/rpc.lua:734 "rpc" "/Users/temp/.local/share/nvim/mason/bin/svelteserver" "stderr" "/Users/temp/.local/share/nvim/mason/packages/svelte-language-server/node_modules/svelte-language-server/dist/src/plugins/typescript/DocumentSnapshot.js:419
 this.paramsPath ||= files.params;
 ^^^

SyntaxError: Unexpected token '||='
 at wrapSafe (internal/modules/cjs/loader.js:1001:16)
 at Module._compile (internal/modules/cjs/loader.js:1049:27)
 at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
 at Module.load (internal/modules/cjs/loader.js:950:32)
 at Function.Module._load (internal/modules/cjs/loader.js:790:12)
 at Module.require (internal/modules/cjs/loader.js:974:19)
 at require (internal/modules/cjs/helpers.js:101:18)
 at Object. (/Users/chrishumboldt/.local/share/nvim/mason/packages/svelte-language-server/node_modules/svelte-language-server/dist/src/plugins/typescript/features/CodeActionsProvider.js:11:28)
 at Module._compile (internal/modules/cjs/loader.js:1085:14)
 at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
"

It has been installed and is managed via Mason.

### Reproduction

Simple:

1. Use Mason to install the server.
2. Try to open a Svelte file.

### Expected behaviour

Parse and correctly validate a Svelte file.

### System Info

- OS: Mac
- IDE: NeoVim

### Which package is the issue about?

svelte-language-server

**Comment by jasonlyu123** [comment]
Your node.js version is too old, and it's not supported anymore. We only support node 16 after [svelte-language-server 0.15.0](https://github.com/sveltejs/language-tools/releases/tag/language-server-0.15.0). Please upgrade your node.js version to 16 or later.

**Comment by chrishumboldt** [comment]
Thank you very much. Have good day mate.
