### ISSUE TITLE
Extension 'Svelte for VS Code' is configured as formatter but it cannot format 'Svelte'-files

### ISSUE THREAD

**Issue by danielniccoli** [sveltejs/language-tools#2137]
I setup my first SvelteKit project (again) and running into issues when I try to format a `.svelte` file. It throws the following error.

> Extension 'Svelte for VS Code' is configured as formatter but it cannot format 'Svelte'-files

I followed the extension's ReadMe for proper configuration. How do I get this extension running?

![image](https://github.com/sveltejs/language-tools/assets/2971735/4e48a1eb-ca2e-4cb1-8d09-842cfb240d3d)

## .vscode/settings.json
```jsonc
{
	"[prisma]": {
		"editor.defaultFormatter": "Prisma.prisma"
	},
	"[svelte]": {
		"editor.defaultFormatter": "svelte.svelte-vscode"
	},
	"editor.defaultFormatter": "esbenp.prettier-vscode",
	"editor.formatOnSave": true,
	"svelte.enable-ts-plugin": true,
	"svelte.plugin.svelte.defaultScriptLanguage": "ts"
}

```

## .prettierrc
```jsonc
{
	"semi": false,
	"useTabs": true,
	"trailingComma": "all",
	"printWidth": 100,
	"plugins": ["prettier-plugin-svelte"],
	"pluginSearchDirs": ["."],
	"overrides": [
		{
			"files": "*.svelte",
			"options": { "parser": "svelte" }
		}
	]
}

```

```svelte
<h1>Factorio Studio</h1>

<form>
	<input type="text" name="title" required>
	<textarea name="content" required />
</form>
```

**Comment by jasonlyu123** [comment]
It might be because the language server crashed or not started yet. Can you check if there is any error logged in the output channels? You can run the "Show Output Channels" command from the command palette (F1) and choose Svelte.

**Comment by danielniccoli** [comment]
Problem went away on its own. Maybe you were right with the language server?

I don't see any errors related to that, but I assume it's just because it was 8 hours ago and I restarted VS Code several times. (Can't be sure, because there are no timestamps in the logs 🙁).

**Comment by danielniccoli** [comment]
I must reopen this issue. I just had it happen again. I wanted to check the Svelte Output Channel again, and it was gone. Below is the output of the **Extension Host** channel. Using the command palette to restart the svelte language server did not help. Restarting VS Code altogether did fix the problem. Hope there's something in the logs that helps finding the cause, so that the server doesn't crash as often.

```
2023-08-25 21:33:41.674 [info] ExtensionService#_doActivateExtension vscode.html-language-features, startup: false, activationEvent: 'onLanguage:html'
2023-08-25 21:34:39.293 [error] Error: Stopping the server timed out
    at c:\Users\niccodan\.vscode\extensions\svelte.svelte-vscode-107.10.0\node_modules\vscode-languageclient\lib\common\client.js:933:23
    at restartLS (c:\Users\niccodan\.vscode\extensions\svelte.svelte-vscode-107.10.0\src\extension.ts:221:9)
    at r.value (c:\Users\niccodan\.vscode\extensions\svelte.svelte-vscode-107.10.0\src\extension.ts:204:13)
2023-08-25 21:43:18.806 [error] Error: Client is not running
    at LanguageClient.sendNotification (c:\Users\niccodan\.vscode\extensions\svelte.svelte-vscode-107.10.0\node_modules\vscode-languageclient\lib\common\client.js:372:35)
    at r.value (c:\Users\niccodan\.vscode\extensions\svelte.svelte-vscode-107.10.0\src\extension.ts:317:21)
    at f.w (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:1902)
    at f.x (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:1972)
    at fire (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:2188)
    at $acceptModelChanged (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:104:10065)
    at t.N (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:114:7983)
    at t.M (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:114:7749)
    at t.H (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:114:6830)
    at t.G (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:114:5906)
    at r.value (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:114:4736)
    at f.w (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:1902)
    at fire (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:2119)
    at y.fire (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:79:13931)
    at r.value (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:130:30355)
    at f.w (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:1902)
    at fire (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:2119)
    at y.fire (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:79:13931)
    at MessagePortMain.<anonymous> (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:130:28635)
    at MessagePortMain.emit (node:events:513:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)
2023-08-25 21:43:18.807 [error] Error: Client is not running
    at LanguageClient.sendNotification (c:\Users\niccodan\.vscode\extensions\svelte.svelte-vscode-107.10.0\node_modules\vscode-languageclient\lib\common\client.js:372:35)
    at r.value (c:\Users\niccodan\.vscode\extensions\svelte.svelte-vscode-107.10.0\src\extension.ts:317:21)
    at f.w (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:1902)
    at f.x (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:1972)
    at fire (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:2188)
    at $acceptDirtyStateChanged (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:104:9746)
    at t.N (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:114:7983)
    at t.M (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:114:7749)
    at t.H (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:114:6830)
    at t.G (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:114:5906)
    at r.value (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:114:4736)
    at f.w (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:1902)
    at fire (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:2119)
    at y.fire (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:79:13931)
    at r.value (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:130:30355)
    at f.w (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:1902)
    at fire (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:2119)
    at y.fire (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:79:13931)
    at MessagePortMain.<anonymous> (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:130:28635)
    at MessagePortMain.emit (node:events:513:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)
2023-08-25 21:43:19.277 [error] Error: Client is not running
    at LanguageClient.sendNotification (c:\Users\niccodan\.vscode\extensions\svelte.svelte-vscode-107.10.0\node_modules\vscode-languageclient\lib\common\client.js:372:35)
    at r.value (c:\Users\niccodan\.vscode\extensions\svelte.svelte-vscode-107.10.0\src\extension.ts:317:21)
    at f.w (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:1902)
    at f.x (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:1972)
    at fire (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:2188)
    at $acceptModelChanged (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:104:10065)
    at t.N (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:114:7983)
    at t.M (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:114:7749)
    at t.H (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:114:6830)
    at t.G (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:114:5906)
    at r.value (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:114:4736)
    at f.w (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:1902)
    at fire (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:2119)
    at y.fire (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:79:13931)
    at r.value (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:130:30355)
    at f.w (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:1902)
    at fire (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:2119)
    at y.fire (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:79:13931)
    at MessagePortMain.<anonymous> (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:130:28635)
    at MessagePortMain.emit (node:events:513:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)
2023-08-25 21:43:19.309 [error] Error: Client is not running
    at LanguageClient.sendNotification (c:\Users\niccodan\.vscode\extensions\svelte.svelte-vscode-107.10.0\node_modules\vscode-languageclient\lib\common\client.js:372:35)
    at r.value (c:\Users\niccodan\.vscode\extensions\svelte.svelte-vscode-107.10.0\src\extension.ts:317:21)
    at f.w (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:1902)
    at f.x (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:1972)
    at fire (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:2188)
    at $acceptDirtyStateChanged (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:104:9746)
    at t.N (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:114:7983)
    at t.M (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:114:7749)
    at t.H (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:114:6830)
    at t.G (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:114:5906)
    at r.value (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:114:4736)
    at f.w (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:1902)
    at fire (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:2119)
    at y.fire (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:79:13931)
    at r.value (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:130:30355)
    at f.w (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:1902)
    at fire (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:2119)
    at y.fire (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:79:13931)
    at MessagePortMain.<anonymous> (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:130:28635)
    at MessagePortMain.emit (node:events:513:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)
2023-08-25 21:43:19.309 [error] Error: Client is not running
    at LanguageClient.sendNotification (c:\Users\niccodan\.vscode\extensions\svelte.svelte-vscode-107.10.0\node_modules\vscode-languageclient\lib\common\client.js:372:35)
    at r.value (c:\Users\niccodan\.vscode\extensions\svelte.svelte-vscode-107.10.0\src\extension.ts:317:21)
    at f.w (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:1902)
    at f.x (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:1972)
    at fire (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:2188)
    at $acceptDirtyStateChanged (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:104:9746)
    at $acceptModelSaved (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:104:9544)
    at t.N (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:114:7983)
    at t.M (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:114:7749)
    at t.H (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:114:6830)
    at t.G (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:114:5906)
    at r.value (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:114:4736)
    at f.w (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:1902)
    at fire (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:2119)
    at y.fire (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:79:13931)
    at r.value (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:130:30355)
    at f.w (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:1902)
    at fire (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:2119)
    at y.fire (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:79:13931)
    at MessagePortMain.<anonymous> (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:130:28635)
    at MessagePortMain.emit (node:events:513:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)
2023-08-25 21:43:48.961 [info] ExtensionService#_doActivateExtension vscode.css-language-features, startup: false, activationEvent: 'onLanguage:css'
2023-08-25 21:45:12.936 [error] Error: Client is not running
    at LanguageClient.sendRequest (c:\Users\niccodan\.vscode\extensions\svelte.svelte-vscode-107.10.0\node_modules\vscode-languageclient\lib\common\client.js:322:35)
    at c:\Users\niccodan\.vscode\extensions\svelte.svelte-vscode-107.10.0\src\extension.ts:348:58
    at E.d (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:100:43502)
    at E.withProgress (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:100:43365)
    at Object.withProgress (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:120:31168)
    at r.value (c:\Users\niccodan\.vscode\extensions\svelte.svelte-vscode-107.10.0\src\extension.ts:345:16)
    at f.w (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:1902)
    at f.x (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:1972)
    at fire (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:2188)
    at b.$onDidRunFileOperation (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:104:29199)
    at t.N (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:114:7983)
    at t.M (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:114:7749)
    at t.H (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:114:6830)
    at t.G (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:114:5906)
    at r.value (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:114:4736)
    at f.w (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:1902)
    at fire (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:2119)
    at y.fire (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:79:13931)
    at r.value (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:130:30355)
    at f.w (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:1902)
    at fire (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:2119)
    at y.fire (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:79:13931)
    at MessagePortMain.<anonymous> (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:130:28635)
    at MessagePortMain.emit (node:events:513:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)
2023-08-25 21:45:18.558 [error] Error: Client is not running
    at LanguageClient.sendRequest (c:\Users\niccodan\.vscode\extensions\svelte.svelte-vscode-107.10.0\node_modules\vscode-languageclient\lib\common\client.js:322:35)
    at c:\Users\niccodan\.vscode\extensions\svelte.svelte-vscode-107.10.0\src\extension.ts:348:58
    at E.d (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:100:43502)
    at E.withProgress (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:100:43365)
    at Object.withProgress (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:120:31168)
    at r.value (c:\Users\niccodan\.vscode\extensions\svelte.svelte-vscode-107.10.0\src\extension.ts:345:16)
    at f.w (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:1902)
    at f.x (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:1972)
    at fire (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:2188)
    at b.$onDidRunFileOperation (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:104:29199)
    at t.N (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:114:7983)
    at t.M (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:114:7749)
    at t.H (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:114:6830)
    at t.G (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:114:5906)
    at r.value (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:114:4736)
    at f.w (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:1902)
    at fire (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:2119)
    at y.fire (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:79:13931)
    at r.value (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:130:30355)
    at f.w (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:1902)
    at fire (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:2119)
    at y.fire (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:79:13931)
    at MessagePortMain.<anonymous> (c:\Users\niccodan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:130:28635)
    at MessagePortMain.emit (node:events:513:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)
```

**Comment by jasonlyu123** [comment]
You might have edited the prettier config file or `svelte.config.js` while the server is busy. Editing these config files will trigger a language server restart. But it timeout presumably because the server process is blocked by some task that took a long time. Does that ring a bell about what you were doing while the crash happened? Have you encountered any performance issues while using the extension in the project that crashes?

**Comment by danielniccoli** [comment]
I don't think I edited that config.

Performance seems fine.

**Comment by dummdidumm** [comment]
The error log is too generic unfortunately, it sounds like a problem higher up the chain. Since it didn't happen again, I'm going to close this. Feel free to ping if it happens again.

**Comment by WoodyWoodsta** [comment]
I'm running into this issue intermittently. Sometimes and on some projects it works, others not. All projects using the same prettier config.

Disabling the svelte extension doesn't solve the issue, so I think this is on the Eslint extension.
