### ISSUE TITLE
Prettier v3 support

### ISSUE THREAD

**Issue by AlexRMU** [sveltejs/language-tools#2197]
### Description

Currently prettier v3 is not supported by the VS Code plugin:
```
Error [ERR_REQUIRE_ESM]: require() of ES Module c:\server\prettier.config.js from c:\Users\User\.vscode\extensions\svelte.svelte-vscode-107.12.0\node_modules\prettier\third-party.js not supported.
Instead change the require of prettier.config.js in c:\Users\User\.vscode\extensions\svelte.svelte-vscode-107.12.0\node_modules\prettier\third-party.js to a dynamic import() which is available in all CommonJS modules.
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at module2.exports (c:\Users\User\.vscode\extensions\svelte.svelte-vscode-107.12.0\node_modules\prettier\third-party.js:83:61)
    at loadJs2 (c:\Users\User\.vscode\extensions\svelte.svelte-vscode-107.12.0\node_modules\prettier\third-party.js:8050:22)
    at Explorer.loadFileContent (c:\Users\User\.vscode\extensions\svelte.svelte-vscode-107.12.0\node_modules\prettier\third-party.js:8449:36)
    at Explorer.createCosmiconfigResult (c:\Users\User\.vscode\extensions\svelte.svelte-vscode-107.12.0\node_modules\prettier\third-party.js:8453:40)
    at Explorer.loadSearchPlace (c:\Users\User\.vscode\extensions\svelte.svelte-vscode-107.12.0\node_modules\prettier\third-party.js:8438:35)
    at async Explorer.searchDirectory (c:\Users\User\.vscode\extensions\svelte.svelte-vscode-107.12.0\node_modules\prettier\third-party.js:8428:31)
    at async run (c:\Users\User\.vscode\extensions\svelte.svelte-vscode-107.12.0\node_modules\prettier\third-party.js:8413:26)
    at async cacheWrapper (c:\Users\User\.vscode\extensions\svelte.svelte-vscode-107.12.0\node_modules\prettier\third-party.js:8294:22)
    at async cacheWrapper (c:\Users\User\.vscode\extensions\svelte.svelte-vscode-107.12.0\node_modules\prettier\third-party.js:8294:22)
    at async cacheWrapper (c:\Users\User\.vscode\extensions\svelte.svelte-vscode-107.12.0\node_modules\prettier\third-party.js:8294:22)
    at async cacheWrapper (c:\Users\User\.vscode\extensions\svelte.svelte-vscode-107.12.0\node_modules\prettier\third-party.js:8294:22)
    at async cacheWrapper (c:\Users\User\.vscode\extensions\svelte.svelte-vscode-107.12.0\node_modules\prettier\third-party.js:8294:22)
    at async cacheWrapper (c:\Users\User\.vscode\extensions\svelte.svelte-vscode-107.12.0\node_modules\prettier\third-party.js:8294:22)
    at async Explorer.search (c:\Users\User\.vscode\extensions\svelte.svelte-vscode-107.12.0\node_modules\prettier\third-party.js:8407:24)
    at async Promise.all (index 0)
    at async getConfig (c:\Users\User\.vscode\extensions\svelte.svelte-vscode-107.12.0\node_modules\svelte-language-server\dist\src\plugins\svelte\SveltePlugin.js:53:67)
    at async importFittingPrettier (c:\Users\User\.vscode\extensions\svelte.svelte-vscode-107.12.0\node_modules\svelte-language-server\dist\src\plugins\svelte\SveltePlugin.js:76:29)
    at async SveltePlugin.formatDocument (c:\Users\User\.vscode\extensions\svelte.svelte-vscode-107.12.0\node_modules\svelte-language-server\dist\src\plugins\svelte\SveltePlugin.js:85:67)
    at async PluginHost.tryExecutePlugin (c:\Users\User\.vscode\extensions\svelte.svelte-vscode-107.12.0\node_modules\svelte-language-server\dist\src\plugins\PluginHost.js:347:20)
    at async Promise.all (index 0)
    at async PluginHost.execute (c:\Users\User\.vscode\extensions\svelte.svelte-vscode-107.12.0\node_modules\svelte-language-server\dist\src\plugins\PluginHost.js:324:24)
    at async PluginHost.formatDocument (c:\Users\User\.vscode\extensions\svelte.svelte-vscode-107.12.0\node_modules\svelte-language-server\dist\src\plugins\PluginHost.js:114:38) {
  code: 'ERR_REQUIRE_ESM'
}
```

### Proposed solution

You need to upgrade prettier to v3 in all packages, not just in prettier-plugin-svelte:
https://github.com/sveltejs/language-tools/blob/663e602da39f118b1936a086612dd4975cdd5db2/packages/language-server/package.json#L55
https://github.com/sveltejs/language-tools/blob/663e602da39f118b1936a086612dd4975cdd5db2/package.json#L20

**Comment by dummdidumm** [comment]
Please provide a reproduction repository. The VS Code extension loads the user's prettier and prettier-plugin-svelte if it exists, and else false back to its built-in version.

**Comment by AlexRMU** [comment]
https://github.com/AlexRMU/sveltejs-language-tools-issues-2197
1. Download the repository and install the dependencies
2. Open any .svelte file
3. Try to format it
4. The following message will appear in the extension console

The problem is that prettier v2 from the extension is trying to import plugins intended for v3

**Comment by jasonlyu123** [comment]
You need to specify `prettier-plugin-svelte` in your `.prettierrc.json`. The bundled prettier-plugin-svelte is v2, so if you don't specify it, we'll fall back to the compatible v2 prettier. But your other plugin needs v3, so it crashes. The reason we didn't bundle v3 is that the majority of users are still in v2. The official prettier extension also does that.

**Comment by AlexRMU** [comment]
Yes, it helped, thank you
