### ISSUE TITLE
Svelte for VS Code keep crashing

### ISSUE THREAD

**Issue by lts20050703** [sveltejs/language-tools#2331]
### Describe the bug

Svelte for VS Code keep crashing

### Reproduction

1. Install Svelte for VS Code (as of writing, the latest Svelte for VS Code version is 108.3.3)
2. `npm install svelte@next` (as of writing, the latest svelte next version is 5.0.0-next.96)
3. Open any svelte file
4. After a few seconds VScodium pop up a message saying that "The Svelte server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information." (The output is provided in the additional information section)

### Expected behaviour

Svelte for VS Code doesn't crash

### System Info

- OS: Linux (KDE Neon 6.0)
- IDE: VSCodium 1.88.0
- svelte (npm): 5.0.0-next.96
- @sveltejs/kit: 2.5.5
- Svelte for VS Code: 108.3.3

### Which package is the issue about?

Svelte for VS Code extension

### Additional Information, eg. Screenshots

In case it isn't obvious, I'm using VSCodium and SvelteKit with `compilerOptions.runes` set to `true`

<details>
<summary>svelte.config.js</summary>

```js
import adapter from "@sveltejs/adapter-node"
import { vitePreprocess } from "@sveltejs/vite-plugin-svelte"
/** @type {import('@sveltejs/kit').Config} */
export default {
	preprocess: vitePreprocess(),
	kit: { adapter: adapter() },
	compilerOptions: { runes: true }
}
```

</details>

<details>
<summary>Svelte for VS Code Extension Output</summary>

```

Node.js v18.18.2
[Info  - 10:15:25 PM] Connection to server got closed. Server will restart.
true
Initialize language server at  file:///home/lts20050703/git/e5y-final
Initialize new ts service at  /home/lts20050703/git/e5y-final/tsconfig.json
Trying to load configs for /home/lts20050703/git/e5y-final
Loaded config at  /home/lts20050703/git/e5y-final/svelte.config.js
node:internal/modules/cjs/loader:1084
  const err = new Error(message);
              ^

Error: Cannot find module '/home/lts20050703/git/e5y-final/node_modules/svelte/compiler.cjs'
Require stack:
- /home/lts20050703/.vscode-oss/extensions/svelte.svelte-vscode-108.3.3-universal/node_modules/svelte-language-server/dist/src/importPackage.js
- /home/lts20050703/.vscode-oss/extensions/svelte.svelte-vscode-108.3.3-universal/node_modules/svelte-language-server/dist/src/lib/documents/configLoader.js
- /home/lts20050703/.vscode-oss/extensions/svelte.svelte-vscode-108.3.3-universal/node_modules/svelte-language-server/dist/src/lib/documents/Document.js
- /home/lts20050703/.vscode-oss/extensions/svelte.svelte-vscode-108.3.3-universal/node_modules/svelte-language-server/dist/src/lib/documents/index.js
- /home/lts20050703/.vscode-oss/extensions/svelte.svelte-vscode-108.3.3-universal/node_modules/svelte-language-server/dist/src/server.js
- /home/lts20050703/.vscode-oss/extensions/svelte.svelte-vscode-108.3.3-universal/node_modules/svelte-language-server/bin/server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1084:15)
    at Module._load (node:internal/modules/cjs/loader:929:27)
    at c._load (node:electron/js2c/node_init:2:13672)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at dynamicRequire (/home/lts20050703/.vscode-oss/extensions/svelte.svelte-vscode-108.3.3-universal/node_modules/svelte-language-server/dist/src/importPackage.js:23:12)
    at importSvelte (/home/lts20050703/.vscode-oss/extensions/svelte.svelte-vscode-108.3.3-universal/node_modules/svelte-language-server/dist/src/importPackage.js:57:12)
    at createLanguageService (/home/lts20050703/.vscode-oss/extensions/svelte.svelte-vscode-108.3.3-universal/node_modules/svelte-language-server/dist/src/plugins/typescript/service.js:117:44)
    at async getServiceForTsconfig (/home/lts20050703/.vscode-oss/extensions/svelte.svelte-vscode-108.3.3-universal/node_modules/svelte-language-server/dist/src/plugins/typescript/service.js:85:19)
    at async LSAndTSDocResolver.getSnapshot (/home/lts20050703/.vscode-oss/extensions/svelte.svelte-vscode-108.3.3-universal/node_modules/svelte-language-server/dist/src/plugins/typescript/LSAndTSDocResolver.js:101:27) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/lts20050703/.vscode-oss/extensions/svelte.svelte-vscode-108.3.3-universal/node_modules/svelte-language-server/dist/src/importPackage.js',
    '/home/lts20050703/.vscode-oss/extensions/svelte.svelte-vscode-108.3.3-universal/node_modules/svelte-language-server/dist/src/lib/documents/configLoader.js',
    '/home/lts20050703/.vscode-oss/extensions/svelte.svelte-vscode-108.3.3-universal/node_modules/svelte-language-server/dist/src/lib/documents/Document.js',
    '/home/lts20050703/.vscode-oss/extensions/svelte.svelte-vscode-108.3.3-universal/node_modules/svelte-language-server/dist/src/lib/documents/index.js',
    '/home/lts20050703/.vscode-oss/extensions/svelte.svelte-vscode-108.3.3-universal/node_modules/svelte-language-server/dist/src/server.js',
    '/home/lts20050703/.vscode-oss/extensions/svelte.svelte-vscode-108.3.3-universal/node_modules/svelte-language-server/bin/server.js'
  ]
}

Node.js v18.18.2
[Error - 10:15:26 PM] The Svelte server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.

```

</details>

**Comment by jasonlyu123** [comment]
There is https://github.com/sveltejs/language-tools/releases/tag/extensions-108.3.4

**Comment by lts20050703** [comment]
> There is https://github.com/sveltejs/language-tools/releases/tag/extensions-108.3.4

I checked for extension updates and VSCodium said that "All extensions are up to date"

Looks like <https://open-vsx.org/extension/svelte/svelte-vscode> wasn't updated?

**Comment by jasonlyu123** [comment]
Hmm. The deploy CI is broken for Open VSX because of the node 18 requirement for the CLI. But we already updated the CI config so it should work in the next release.
