### ISSUE TITLE
Extension keep crashing: MarkCompactCollector

### ISSUE THREAD

**Issue by Extarys** [sveltejs/language-tools#2510]
### Describe the bug

Every time I try to run "Format document", after 10-20 seconds I get an error in Output > Svelte and nothing happens
```

<--- Last few GCs --->

[1079:0x63000364000]    76965 ms: Scavenge 3914.9 (4084.8) -> 3912.1 (4087.0) MB, pooled: 0 MB, 4.13 / 0.00 ms  (average mu = 0.814, current mu = 0.575) allocation failure; 
[1079:0x63000364000]    76986 ms: Scavenge 3917.1 (4087.0) -> 3914.2 (4089.5) MB, pooled: 0 MB, 7.72 / 0.00 ms  (average mu = 0.814, current mu = 0.575) allocation failure; 


<--- JS stacktrace --->

FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory
----- Native stack trace -----

[Error - 20:51:07] Server process exited with signal SIGABRT.
[Info  - 20:51:07] Connection to server got closed. Server will restart.
true
Initialize language server at  file:///srv/repo
Initialize new ts service at  /srv/repo/apps/ui/tsconfig.json
Trying to load configs for /srv/repo/apps/ui
Loaded config at  /srv/repo/apps/ui/svelte.config.js
SnapshotManager File Statistics:
Project files: 295
Svelte files: 212
From node_modules: 0
Total: 295
No svelte.config.js found. Using https://github.com/sveltejs/svelte-preprocess as fallback
No svelte.config.js found. Using https://github.com/sveltejs/svelte-preprocess as fallback
```
(I have a lot of those)

Output > Extension Host
```
2024-09-20 21:15:10.088 [error] Error: Pending response rejected since connection got disposed
	at Object.dispose (/home/user/.var/app/com.vscodium.codium/data/codium/extensions/svelte.svelte-vscode-109.0.1-universal/node_modules/vscode-jsonrpc/lib/common/connection.js:1167:27)
	at Object.dispose (/home/user/.var/app/com.vscodium.codium/data/codium/extensions/svelte.svelte-vscode-109.0.1-universal/node_modules/vscode-languageclient/lib/common/client.js:1586:35)
	at LanguageClient.handleConnectionClosed (/home/user/.var/app/com.vscodium.codium/data/codium/extensions/svelte.svelte-vscode-109.0.1-universal/node_modules/vscode-languageclient/lib/common/client.js:1155:34)
	at LanguageClient.handleConnectionClosed (/home/user/.var/app/com.vscodium.codium/data/codium/extensions/svelte.svelte-vscode-109.0.1-universal/node_modules/vscode-languageclient/lib/node/main.js:180:22)
	at closeHandler (/home/user/.var/app/com.vscodium.codium/data/codium/extensions/svelte.svelte-vscode-109.0.1-universal/node_modules/vscode-languageclient/lib/common/client.js:1142:18)
	at CallbackList.invoke (/home/user/.var/app/com.vscodium.codium/data/codium/extensions/svelte.svelte-vscode-109.0.1-universal/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/home/user/.var/app/com.vscodium.codium/data/codium/extensions/svelte.svelte-vscode-109.0.1-universal/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at closeHandler (/home/user/.var/app/com.vscodium.codium/data/codium/extensions/svelte.svelte-vscode-109.0.1-universal/node_modules/vscode-jsonrpc/lib/common/connection.js:314:26)
	at CallbackList.invoke (/home/user/.var/app/com.vscodium.codium/data/codium/extensions/svelte.svelte-vscode-109.0.1-universal/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/home/user/.var/app/com.vscodium.codium/data/codium/extensions/svelte.svelte-vscode-109.0.1-universal/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at IPCMessageReader.fireClose (/home/user/.var/app/com.vscodium.codium/data/codium/extensions/svelte.svelte-vscode-109.0.1-universal/node_modules/vscode-jsonrpc/lib/common/messageReader.js:41:27)
	at ChildProcess.<anonymous> (/home/user/.var/app/com.vscodium.codium/data/codium/extensions/svelte.svelte-vscode-109.0.1-universal/node_modules/vscode-jsonrpc/lib/node/main.js:37:45)
	at ChildProcess.emit (node:events:531:35)
	at maybeClose (node:internal/child_process:1105:16)
	at Socket.<anonymous> (node:internal/child_process:457:11)
	at Socket.emit (node:events:519:28)
	at Pipe.<anonymous> (node:net:338:12)
```

### Reproduction

I have this issue with VSCodium rpm and VSCodium flatpak. **No idea how to reproduce.**

Monorepo with a ui folder, containing svelte.config.js (Sveltekit, vite).

Formatting work on a 25 LOC file, but another component with 95 LOC make it crash every single time. I tried multiple page and they mostly all make the language server crash.

**I don't really know what you need, please let me know.** It was working fine 2 days ago, I didn't update any npm package, but I have no idea if vscode did update extensions in the background, so I erased all tmp and config files and tested with flatpak too, issue still persist.

### Expected behaviour

The extension shouldn't crash;
The document should get formatted

### System Info

- OS: Fedora 40 KDE
- IDE
- Version: 1.93.1
Release: 24256
Commit: dbab3f8e8c5da7ca1bde636806e0a973e497aa01
Date: 2024-09-12T18:27:33.186Z
Electron: 30.4.0
ElectronBuildId: undefined
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Linux x64 6.10.10-200.fc40.x86_64

### Which package is the issue about?

Svelte for VS Code extension, svelte-language-server

### Additional Information, eg. Screenshots

Old similar issue: https://github.com/jamesbirtles/svelte-vscode/issues/26

**Comment by jasonlyu123** [comment]
We'll definitely need a reproduction to help you. Formatting usually only works with the current file so it shouldn't use that much memory that would crash the process. I suspect it might be some infinite loop/recursive call. Can you try copying the problematic files or the prettier config file to an empty svelte-kit project to see if you can reproduce it? If you still can't find a reproduction, please at least provide the dependencies and devDependencies in your package.json, the tsconfig.json/jsconfig.json and the prettier config file.

**Comment by jasonlyu123** [comment]
Can follow these steps to collect a cpu profile. At least we could know what was running before memory exploded. 

1. Set the "svelte.language-server.port": config to 9222.
2.  Restart your editor and open a svelte file.
3.  Open Chrome or Edge and type chrome://inspect. Wait a bit. There should be a svelte language server, and you can inspect
4. A dev tool will open After you click the inspect link. You can record a CPU profile in the performance tab. If the performance tab is empty, click the gear icon on the top right, go to "Experimentals" and disable "Performance panel: enable live metrics landing page"
5. export the recording. you can open the output file in an editor to remove sensitive info like file path.
