### ISSUE TITLE
Svelte Extension crashing on startup of VSCode (insiders / macOS 11.2 / M1)

### ISSUE THREAD

**Issue by neiled** [sveltejs/language-tools#794]
**Describe the bug**
Upon starting vscode the error 'The svelte server crashed 5 times in the last 3 minutes..."
Stack trace at bottom. 

**To Reproduce**

Unknown I only have one system to try it on, but version numbers:
Svelte for VS Code 104.2.1
Visual Studio Code - Insiders: Version: 1.53.0-insider

**Expected behavior**
Extension to start without erroring

**Screenshots**

**System (please complete the following information):**
 - OS: MacOS 11.2
 - IDE: Visual Studio Code - Insiders: Version: 1.53.0-insider
 - Plugin/Package: Svelte for VS Code 104.2.1

**Additional context**
```

Initialize language server at  file:///Users/neiled/dev/sapper-1
Trying to load config for /Users/neiled/dev/sapper-1/src/components/Nav.svelte
No svelte.config.js found. Using https://github.com/sveltejs/svelte-preprocess as fallback
Using svelte-preprocess v4.6.3 from /Users/neiled/dev/sapper-1/node_modules/svelte-preprocess
Initialize new ts service at  /Users/neiled/dev/sapper-1/tsconfig.json
SnapshotManager File Statistics:
Project files: 9
Svelte files: 0
From node_modules: 2
Total: 9


#
# Fatal error in , line 0
# ignored
#
#
#
#FailureMessage Object: 0x16d481b38
 1: 0x1052dc8f8 node::MultiIsolatePlatform::CancelPendingDelayedTasks(v8::Isolate*) [/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 2: 0x10765a174 v8::internal::compiler::ZoneStats::GetCurrentAllocatedBytes() const [/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 3: 0x1062810fc v8::internal::wasm::NativeModule::NativeModule(v8::internal::wasm::WasmEngine*, v8::internal::wasm::WasmFeatures const&, v8::internal::VirtualMemory, std::__1::shared_ptr<v8::internal::wasm::WasmModule const>, std::__1::shared_ptr<v8::internal::Counters>, std::__1::shared_ptr<v8::internal::wasm::NativeModule>*) [/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 4: 0x103744368 v8::internal::wasm::NativeModule::AddCodeSpace(v8::base::AddressRegion, v8::internal::wasm::WasmCodeAllocator::OptionalLock const&) [/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 5: 0x1062823f0 v8::internal::wasm::NativeModule::FreeCode(v8::internal::Vector<v8::internal::wasm::WasmCode* const>) [/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 6: 0x10628fc0c v8::internal::wasm::WasmEngine::FreeDeadCodeLocked(std::__1::unordered_map<v8::internal::wasm::NativeModule*, std::__1::vector<v8::internal::wasm::WasmCode*, std::__1::allocator<v8::internal::wasm::WasmCode*> >, std::__1::hash<v8::internal::wasm::NativeModule*>, std::__1::equal_to<v8::internal::wasm::NativeModule*>, std::__1::allocator<std::__1::pair<v8::internal::wasm::NativeModule* const, std::__1::vector<v8::internal::wasm::WasmCode*, std::__1::allocator<v8::internal::wasm::WasmCode*> > > > > const&) [/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 7: 0x10628e524 v8::internal::wasm::WasmEngine::PotentiallyFinishCurrentGC() [/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 8: 0x10628f38c v8::internal::wasm::WasmEngine::ReportLiveCodeForGC(v8::internal::Isolate*, v8::internal::Vector<v8::internal::wasm::WasmCode*>) [/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 9: 0x10628f458 v8::internal::wasm::WasmEngine::ReportLiveCodeFromStackForGC(v8::internal::Isolate*) [/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
10: 0x1052db3ac node::Buffer::New(v8::Isolate*, char*, unsigned long, void (*)(char*, void*), void*) [/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
11: 0x1052da340 node::Buffer::New(v8::Isolate*, char*, unsigned long, void (*)(char*, void*), void*) [/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
12: 0x102b6a32c uv_async_send [/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
13: 0x102b7a6c8 uv_free_interface_addresses [/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
14: 0x102b6a768 uv_run [/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
15: 0x102cedea0 ElectronInitializeICUandStartNode [/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
16: 0x102b7ad4c ElectronInitializeICUandStartNode [/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
17: 0x1029769f8  [/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper (Renderer).app/Contents/MacOS/Code - Insiders Helper (Renderer)]
18: 0x197c09f34 start [/usr/lib/system/libdyld.dylib]
[Error - 8:11:17 PM] Connection to server got closed. Server will not be restarted.
[Error - 8:11:17 PM] Request textDocument/semanticTokens/range failed.
Error: Connection got disposed.
	at Object.dispose (/Users/neiled/.vscode-insiders/extensions/svelte.svelte-vscode-104.2.1/node_modules/vscode-jsonrpc/lib/common/connection.js:1044:27)
	at Object.dispose (/Users/neiled/.vscode-insiders/extensions/svelte.svelte-vscode-104.2.1/node_modules/vscode-languageclient/lib/common/client.js:73:35)
	at LanguageClient.handleConnectionClosed (/Users/neiled/.vscode-insiders/extensions/svelte.svelte-vscode-104.2.1/node_modules/vscode-languageclient/lib/common/client.js:2424:42)
	at LanguageClient.handleConnectionClosed (/Users/neiled/.vscode-insiders/extensions/svelte.svelte-vscode-104.2.1/node_modules/vscode-languageclient/lib/node/main.js:155:15)
	at closeHandler (/Users/neiled/.vscode-insiders/extensions/svelte.svelte-vscode-104.2.1/node_modules/vscode-languageclient/lib/common/client.js:2411:18)
	at CallbackList.invoke (/Users/neiled/.vscode-insiders/extensions/svelte.svelte-vscode-104.2.1/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/Users/neiled/.vscode-insiders/extensions/svelte.svelte-vscode-104.2.1/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at closeHandler (/Users/neiled/.vscode-insiders/extensions/svelte.svelte-vscode-104.2.1/node_modules/vscode-jsonrpc/lib/common/connection.js:256:26)
	at CallbackList.invoke (/Users/neiled/.vscode-insiders/extensions/svelte.svelte-vscode-104.2.1/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/Users/neiled/.vscode-insiders/extensions/svelte.svelte-vscode-104.2.1/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at IPCMessageReader.fireClose (/Users/neiled/.vscode-insiders/extensions/svelte.svelte-vscode-104.2.1/node_modules/vscode-jsonrpc/lib/common/messageReader.js:40:27)
	at ChildProcess.<anonymous> (/Users/neiled/.vscode-insiders/extensions/svelte.svelte-vscode-104.2.1/node_modules/vscode-jsonrpc/lib/node/main.js:33:45)
	at ChildProcess.emit (events.js:327:22)
	at maybeClose (internal/child_process.js:1021:16)
	at Socket.<anonymous> (internal/child_process.js:443:11)
	at Socket.emit (events.js:315:20)
	at Pipe.<anonymous> (net.js:674:12
```

**Comment by jasonlyu123** [comment]
Can you try setting the [svelte.language-server.runtime](https://github.com/sveltejs/language-tools/tree/master/packages/svelte-vscode#sveltelanguage-serverruntime)? This would use your own version of node instead of the bundled version of vscode. If that doesn't work maybe you can try to install the latest version of the node. I suspect it's sourcemap or some other native library not compatible with the combination of node and macOS.

**Comment by neiled** [comment]
Hi, that worked, setting it to current node lts version I have installed stopped the issue from happening.

**Comment by dummdidumm** [comment]
Possible causes: https://github.com/nodejs/node/issues/37061 , https://github.com/microsoft/vscode/issues/115646

**Comment by jasonlyu123** [comment]
Reading through the comments of the node thread got me curious about what version of node did you got it working.

**Comment by neiled** [comment]
Current LTS version. So not arm based. Still running through Rosetta I guess.

**Comment by callahad** [comment]
Wading through the issues above: This seems to be an [upstream bug with V8](https://bugs.chromium.org/p/v8/issues/detail?id=11389) on ARM under macOS.

Rosetta2 is a viable workaround, either by running an Intel build of VSCode and using its built-in runtime, or using an ARM version of VSCode and pointing `svelte.language-server.runtime` at an Intel version of the Node executable.

**Comment by dummdidumm** [comment]
This may have been fixed, the vs code issue was closed. Could someone try again?

**Comment by Valexr** [comment]
Yep - i'm trying but still error...

**Comment by callahad** [comment]
This is successfully working for me on the latest VSCode Insiders build, specifically:

Version: 1.54.0-insider
Commit: 52838cf6799cc448e738677ec37e86cf62a5bd89
Date: 2021-02-05T05:17:08.594Z
Electron: 11.2.2
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin arm64 20.3.0

**Comment by Valexr** [comment]
Yep! Working now )))

**Comment by dummdidumm** [comment]
Closing as I think the upstream issues are resolved. If there are still problems feel free to comment.
